### ISSUE TITLE
Add controller manager configuration (for alpha)

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#101]
The controller manager currently runs all controllers.  Ideally it would be possible to control whether each controller is started.  Flags is a quick-n-dirty solution to this, and probably preferable if controllers are likely to live in separate repos post-alpha.  A more maintainable solution might be storing configuration as ConfigMap (or whatever the current best practice is for Kube components).

**Comment by pmorie** [comment]
We should be using feature gates for this type of configuration.

**Comment by marun** [comment]
I think this is satisfied by #105.
