### ISSUE TITLE
Rename kubefnord to something more appropriate

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes-sigs/federation-v2#103]
Seems like we can do a lot better than fnord w.r.t. understandability

https://en.wikipedia.org/wiki/Fnord

kubefed ?
fedctl ?

**Comment by gyliu513** [comment]
+1 to fedctl

**Comment by marun** [comment]
@irfanurrehman Assigning to you, already tracked in the milestone.

**Comment by marun** [comment]
Fixed by #149
