### ISSUE TITLE
Retrigger CI build

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes-sigs/federation-v2#106]
How to trigger a CI build if one fails due to temporary issue in network? Here is one such [failure](https://travis-ci.org/kubernetes-sigs/federation-v2/builds/388795665?utm_source=github_status&utm_medium=notification) and i am unaware of the method to re-trigger the build. This could be a frequent issue to a developer. 

/cc @kubernetes-sigs/federation-wg

**Comment by font** [comment]
When we eventually move to test-infra we should be able to use bot commands. In the meantime for Travis, there should be a restart build button at the top right.

![screenshot from 2018-06-06 08-49-27](https://user-images.githubusercontent.com/3596535/41049793-92c5490e-6966-11e8-95a8-0dd1c9d7165a.png)

**Comment by shashidharatd** [comment]
Cool, Thanks for the info @font. I was able to restart the build.
/close
