### ISSUE TITLE
Align FederatedCluster with cluster-registry

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#110]
In 0.0.5, the cluster-registry becomes namespaced; currently, our `FederatedCluster` resource is cluster-scoped. We should align `FederatedCluster` with `Cluster` by making it namespaced. As part of this, we should decide how federation should use the 'globally readable' namespace in the cluster-registry.

**Comment by gyliu513** [comment]
This is related to https://github.com/kubernetes-sigs/federation-v2/issues/76
