### ISSUE TITLE
Stop relying on apiserver-boot run in-cluster

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#112]
Currently, the `scripts/deploy_federation.sh` runs `apiserver-boot run in-cluster` to deploy the federation bits into a cluster. We should instead have a set of resources (statically defined is fine at first, we might consider a helm chart or other form of packaging in the future) that can be deployed without requiring the user to have a dependency installed.

This likely depends on #82 to be usable.

**Comment by marun** [comment]
This is fixed by #120 (switch to kubebuilder).
