### ISSUE TITLE
How to deploy storage-provisioner

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#117]
At step https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#deploy-the-cluster-registry , it is requested to create `storage-provisioner`. Any steps can help me to set up this?

## Deploy the Cluster Registry
Make sure the storage provisioner is ready before deploying the Cluster Registry.

kubectl -n kube-system get pod storage-provisioner

**Comment by onyiny-ang** [comment]
This is just specifying a check. Once you have your kubernetes clusters running, use `kubectl -n kube-system get pod storage-provisioner` and make sure the status is RUNNING with READY 1/1.
If you're using minikube, this should be working once your minikube clusters are spun up.

**Comment by gyliu513** [comment]
Thanks @onyiny-ang I'm not using mini-kube, does the `storage-provisioner` must be installed?

Also cluster-registry already switched to CRD and there will be no binaries such as crinit etc, the user guide needs to be updated. Updating the user guide to make people can try this is always a good way to attract more contributors.

**Comment by onyiny-ang** [comment]
@gyliu513 we are aware of the cluster-registry being switched to CRDs and are working on integrating that into the federation-v2 alpha release as can be seen in such issues as #76 and the v1alpha1 milestone. We will certainly update the user guide accordingly when the cluster-registry CRD and move to kube builder is incorporated--hopefully in the next couple of weeks. Today federation-v2 relies on the crinit binary (and non-namespaced cluster-registry).
I don't think you need to worry about the `storage-provisioner` if you are not using minikube.

**Comment by gyliu513** [comment]
@onyiny-ang we do have logic here https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/deploy-federation.sh#L76-L83 waiting for the storage provider, can I delete this from the script when deploy?

Does crinit need this storage provider to create some pv for etcd?

**Comment by onyiny-ang** [comment]
@gyliu513 I would suggest commenting out that logic on your local version of deploy-federation if you're using something other than minikube as it only applies to minikube instances. Other than that, the script should work outside of minikube as well.

**Comment by gyliu513** [comment]
Thanks @onyiny-ang , let me have a try for this.
