### ISSUE TITLE
Where to get federation image

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#118]
In step https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#automated-deployment , 

## Automated Deployment
If you would like to have the deployment of the cluster registry and federation-v2 control plane automated, then invoke the deployment script by running:

./scripts/deploy-federation.sh <image> cluster2
Where <image> is in the form <containerregistry>/<username>/<imagename>:<tagname> e.g. docker.io/<username>/federation-v2:test.

Where to get the image of `federation-v2:test`?

Any steps for me to build this image?

**Comment by onyiny-ang** [comment]
@gyliu513 we are currently working on creating a pre-built image for use with the deploy federation script but currently, the apiserver-builder will build the federation image for you as explained here: https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#deploy-federation
So for example:
if I'm using google container registry and my username is onyinyang, following the specification:
<containerregistry>/<username>/<imagename>:<tagname> \
my image name would be:
gcr.io/onyinyang/federation:v2

where the imagename and tagname can be arbitrary. If the image doesn't already exist, apiserver-builder will create it for you.

**Comment by gyliu513** [comment]
Thanks @onyiny-ang , let me have a try for this.
