### ISSUE TITLE
Pre-commit.sh TestFederatedDeploymentOverride is flakey

### ISSUE THREAD

**Issue by onyiny-ang** [kubernetes-sigs/federation-v2#121]
**What happened:** 
pre-commit.sh failed with `The command "./scripts/pre-commit.sh" exited with 1.` during PR merge that didn't change any files involved with pre-commit.
Upon closer inspection, the FederatedDeploymentOverride test was the site of failure. with `E0622 19:32:33.123174    7101 runtime.go:66] Observed a panic: "close of closed channel" (close of closed channel)`

<details>
 <summary>FederatedDeploymentOverride test failure message</summary>
 
```
 === RUN   TestFederatedDeploymentOverride
Running Suite: FederatedDeploymentOverride Suite
================================================
Random Seed: 1529695950
Will run 1 of 1 specs
[::]:34070
[::]:39911
[::]:36361
I0622 19:32:31.545945    7101 serving.go:295] Generated self-signed cert (/tmp/apiserver-test619575690/.crt, /tmp/apiserver-test619575690/.key)
W0622 19:32:31.822413    7101 authorization.go:34] Authorization is disabled
W0622 19:32:31.822450    7101 authentication.go:56] Authentication is disabled
I0622 19:32:32.734425    7101 serve.go:89] Serving securely on [::]:36361
2018-06-22 19:32:32.953433 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:32.953859 I | Validating fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:32.984759 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:32.996063 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:33.005890 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:33.009944 I | Running reconcile FederatedDeploymentOverride for instance-1
2018-06-22 19:32:33.102584 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:33.105992 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:33.110035 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:33.110369 I | Defaulting fields for FederatedDeploymentOverride instance-1
2018-06-22 19:32:33.110771 I | Defaulting fields for FederatedDeploymentOverride instance-1
•E0622 19:32:33.123174    7101 runtime.go:66] Observed a panic: "close of closed channel" (close of closed channel)
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:573
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/chan.go:333
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:529
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:388
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361
panic: close of closed channel [recovered]
	panic: close of closed channel
goroutine 1241 [running]:
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x17bef60, 0x447d820)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache.(*processorListener).pop(0xc420a98d00)
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:529 +0x29c
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache.pop)-fm()
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:388 +0x2a
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4214abcc8, 0xc4222a8d70)
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
FAIL	github.com/kubernetes-sigs/federation-v2/pkg/controller/federateddeploymentoverride	3.184s
=== RUN   TestFederatedDeploymentPlacement
Running Suite: FederatedDeploymentPlacement Suite
=================================================
`` `

</details>

**Comment by onyiny-ang** [comment]
Observed the same error for Test Federated Job too.

<details>
 <summary>Federated Job test failure message</summary>
 `=== RUN   TestFederatedJob
Running Suite: FederatedJob Suite
=================================
Random Seed: 1530521791
Will run 1 of 1 specs
[::]:33488
[::]:41503
[::]:37822
I0702 08:56:32.943518    7089 serving.go:295] Generated self-signed cert (/tmp/apiserver-test051189648/.crt, /tmp/apiserver-test051189648/.key)
W0702 08:56:33.236384    7089 authorization.go:34] Authorization is disabled
W0702 08:56:33.236417    7089 authentication.go:56] Authentication is disabled
I0702 08:56:34.017763    7089 serve.go:89] Serving securely on [::]:37822
2018-07-02 08:56:35.297964 I | Defaulting fields for FederatedJob instance-1
2018-07-02 08:56:35.298498 I | Validating fields for FederatedJob instance-1
2018-07-02 08:56:35.300369 I | Defaulting fields for FederatedJob instance-1
2018-07-02 08:56:35.300803 I | Defaulting fields for FederatedJob instance-1
2018-07-02 08:56:35.301842 I | Defaulting fields for FederatedJob instance-1
I0702 08:56:35.302394    7089 trace.go:76] Trace[919889828]: "Create /apis/federation.k8s.io/v1alpha1/namespaces/federatedjob-controller-test-handler/federatedjobs" (started: 2018-07-02 08:56:34.297706191 +0000 UTC m=+2.831385697) (total time: 1.00465004s):
Trace[919889828]: [1.000592899s] [1.000565107s] Conversion done
2018-07-02 08:56:35.303879 I | Running reconcile FederatedJob for instance-1
2018-07-02 08:56:35.307941 I | Defaulting fields for FederatedJob instance-1
2018-07-02 08:56:35.308886 I | Defaulting fields for FederatedJob instance-1
2018-07-02 08:56:35.309959 I | Defaulting fields for FederatedJob instance-1
2018-07-02 08:56:35.310353 I | Defaulting fields for FederatedJob instance-1
2018-07-02 08:56:35.311037 I | Defaulting fields for FederatedJob instance-1
•E0702 08:56:35.314062    7089 runtime.go:66] Observed a panic: "close of closed channel" (close of closed channel)
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:573
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/chan.go:333
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:529
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:388
/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361
panic: close of closed channel [recovered]
	panic: close of closed channel
goroutine 1279 [running]:
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x17beee0, 0x447d6e0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache.(*processorListener).pop(0xc4237b5700)
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:529 +0x29c
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache.pop)-fm()
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/client-go/tools/cache/shared_informer.go:388 +0x2a
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4210cb9b8, 0xc4240e29a0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
FAIL	github.com/kubernetes-sigs/federation-v2/pkg/controller/federatedjob	3.860s`
</details>

**Comment by marun** [comment]
We haven't seen this in some time, closing.
