### ISSUE TITLE
Upgrade kubebuilder to 0.1.12

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#128]
cluster-registry kubebuilder has been upgraded to 0.1.12 at https://github.com/kubernetes/cluster-registry/pull/244 , it is better upgrade federation v2 to this version as well.

/cc @marun

**Comment by marun** [comment]
I don't think it's desirable to update to the version of kubebuilder referenced in this issue.  @pmorie has recently made changes that add support for the status subresource, and ideally a version including that change should be targeted.  There does not need to be a correlation between the versions of kubebuilder used  for cluster registry and federation.

**Comment by gyliu513** [comment]
@marun with Kubebuild 0.1.12, we will not need to update `status subresources` as this was alraedy fixed in 0.1.12 at https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v0.1.12

![image](https://user-images.githubusercontent.com/4461983/42151175-af121e86-7e0e-11e8-9a16-f42b8035f42b.png)

@pmorie comments for this?

**Comment by marun** [comment]
It turned out to be necessary to use kubebuilder 1.12 (via `scripts/download-binaries.sh`) in #120.  It doesn't appear necessary to update the vendored version of kubebuilder at this time, though, so I think it's safe to close for now.
