### ISSUE TITLE
Add support for building tagged images

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#152]
Once we begin releasing tagged versions, we will need to release tagged images. This issue is to update the existing image build to work with tagged versions such that:

- When building a tag, the image pushed will be tagged with the version being built; example: travis build of `0.0.1` tag results in `federation-v2:0.0.1` image being pushed
- The binaries in the image report a version consistent with the tag; example: `controller-manager --version` reports `0.0.1` from the `federation-v2:0.0.1` image

**Comment by shashidharatd** [comment]
@pmorie, this has been addressed. Please reopen if you feel otherwise.
