### ISSUE TITLE
Multi-cluster namespaces are sometimes not deleted in joined clusters

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/federation-v2#163]
If you run through the [Example](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#example) in the user guide after #157 merges, you will see that after running through the [Example Cleanup](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#example-cleanup), the `test-namespace` is sometimes not deleted from `cluster2`.

**Comment by marun** [comment]
@font Can you still reproduce this?  Namespace garbage collection is often problematic and it would be useful to determine the source of the problem.

**Comment by font** [comment]
Closing as this has since been fixed.
