### ISSUE TITLE
Federation base image to busybox

### ISSUE THREAD

**Issue by runonautomation** [kubernetes-sigs/federation-v2#173]
Dear team,
I am looking to the development process and from development prospective and k8s integration. I see that the image build is great and uses multi-stage build.

I have following suggestions:
- If the strategy is to be as tight as possible integrated with kubernetes - use same build image flow as in kubernetes and use the same base image and maybe process in:
https://github.com/kubernetes/kubernetes/tree/master/build

- Or use a lighter image in second stage, like busybox that in this case most probably will work fine in the same way.

Stats for current build image size currently are following:
federation-v2-kube-debian-base - 86.4MB 
federation-v2-ubuntu - 125MB (current ubuntu latest)
federation-v2-busybox - 44.5MB (the one that for example gcr.io/google-containers/kube-apiserver-amd64 uses, set in here: https://github.com/kubernetes/kubernetes/blob/master/build/common.sh)

I personally think busybox like in common k8s build might be an option.

**Comment by marun** [comment]
I think this issue can be considered resolved by the switch to alpine in #416.
