### ISSUE TITLE
Migrate code structure to kubebuilder v1.0.x

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes-sigs/federation-v2#208]
- kubebuilder 1.0.0 introduces big architectural change in the project/code structure. 1.0.0 projects uses client and controller libraries developed under controller-runtime repo. It uses tools from controller-tools repo for scaffolding and manifests (CRD/RBAC) generation.
- 1.0.0 will continue to support projects generated using older version (pre 1.0.0 version) of Kubebuilder, but we would highly recommend migrating to newer version. Follow instructions for migration your project to 1.0.0 version.

I know this is not a urgent issue for us as of now. just adding it to backlog.
/cc @marun @gyliu513 @kubernetes-sigs/federation-wg

**Comment by gyliu513** [comment]
Thanks @shashidharatd .

There is a WIP PR here https://github.com/kubernetes-sigs/federation-v2/pull/148 , hope we can get more comments from @marun to see when we can do the migration.

**Comment by marun** [comment]
@gyliu513 Upgrading the binaries is fine.  Migrating to the new client-less framework should wait until after #60, which I'll be tackling after #216 is complete.

**Comment by gyliu513** [comment]
@marun yes, I only created PR https://github.com/kubernetes-sigs/federation-v2/pull/250 to update binaries based on your comments.

**Comment by marun** [comment]
I think the next steps for this issue are: 

 - Replacing all calls to the generated clients with equivalent calls to the `controller-runtime` generic client
 - Removing the generated clients (and the `+genclient` annotation on the types to prevent regeneration)

Here is an example of a call to a generated client:

```golang
fedClient := fedclientset.NewForConfigOrDie(kubeConfig).
typeConfig, err := fedClient.CoreV1alpha1().FederatedTypeConfigs(namespace).Get(name, metav1.GetOptions{})
```

Here is an equivalent call with the generic client:

```golang
// Assumes import of: 
//    - "context"
//    - "sigs.k8s.io/controller-runtime/pkg/client"

genericClient, err := client.New(kubeConfig, client.Options{})
if err != nil {
...
}
typeConfig := &fedv1a1.FederatedTypeConfig{}
key := client.ObjectKey{Name: name, Namespace: namespace}
err := genericClient.Get(context.Background(), key, typeConfig)
```

**Comment by shashidharatd** [comment]
This is addressed with https://github.com/kubernetes-sigs/federation-v2/pull/716
