### ISSUE TITLE
Incomplete Pluralization of Types

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#219]
53566d9fc6d4062f9c15504af7dda5bf5c42e81b pluralizes federated types ending with "s", such as `Ingress`. However, adding "es" to federated types should be extended beyond suffixes ending with "s".

I will submit a PR to fix this issue following the proper pluralization [guidelines](https://howtospell.co.uk/adding-es-plural-rule).

**Comment by marun** [comment]
Fixed by #221
