### ISSUE TITLE
delete-federation.sh does not delete FederatedTypeConfig Resources

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#227]
The script is missing the namespace in the kubectl delete command. Therefore, these resources never get removed and the script hangs.

To reproduce:
- Follow the user guide to deploy the k8s clusters, federation control-plane, etc..
- Run the delete script `./scripts/delete-federation.sh` and watch it hang:
```
$ ./scripts/delete-federation.sh
I0822 19:02:15.333154   11916 unjoin.go:108] Defaulting cluster context to unjoining cluster name cluster1
I0822 19:02:15.333230   11916 unjoin.go:112] Args and flags: name cluster1, host-cluster-context: cluster1, host-system-namespace: federation-system, kubeconfig: , cluster-context: cluster1, dry-run: false
I0822 19:02:15.348216   11916 unjoin.go:166] Performing preflight checks for unjoin cluster: cluster1.
I0822 19:02:15.371019   11916 unjoin.go:253] Removing cluster: cluster1 from the cluster registry.
I0822 19:02:15.376334   11916 unjoin.go:261] Removed cluster: cluster1 from the cluster registry.
I0822 19:02:15.376374   11916 unjoin.go:179] Deleting federated cluster resource from namespace: federation-system for unjoin cluster: cluster1
I0822 19:02:15.388857   11916 unjoin.go:190] Deleted federated cluster resource from namespace: federation-system for unjoin cluster: cluster1
I0822 19:02:15.388885   11916 unjoin.go:317] Deleting cluster role binding for service account: cluster1-cluster1 in unjoining cluster: cluster1
I0822 19:02:15.399518   11916 unjoin.go:328] Deleted cluster role binding for service account: cluster1-cluster1 in unjoining cluster: cluster1
I0822 19:02:15.399542   11916 unjoin.go:331] Deleting service account cluster1-cluster1 in unjoining cluster: cluster1
I0822 19:02:15.403215   11916 unjoin.go:338] Deleted service account cluster1-cluster1 in unjoining cluster: cluster1
I0822 19:02:15.403239   11916 unjoin.go:201] Host cluster: cluster1 and unjoin cluster: cluster1 are same, no need to delete federation namespace: federation-system from unjoin cluster.
customresourcedefinition.apiextensions.k8s.io "clusters.clusterregistry.k8s.io" deleted
namespace "kube-multicluster-public" deleted

^C
```

Then check for the existence of `federatedtypeconfig` resources:
```
$ kubectl get federatedtypeconfig --all-namespaces
NAMESPACE           NAME                   AGE
federation-system   configmaps             1h
federation-system   deployments.apps       1h
federation-system   ingresses.extensions   1h
federation-system   jobs.batch             1h
federation-system   namespaces             1h
federation-system   replicasets.apps       1h
federation-system   secrets                1h
federation-system   services               1h
```

I will submit a PR to fix this issue.

**Comment by marun** [comment]
@danehans Thanks for catching this, we don't have ci testing for the deletion script since it's primarily a developer aid.  How did you determine that deletion of FederatedTypeConfig resources was hanging?  The deletion command being invoked ignores missing resources, and when not provided a namespace kubectl will use the active namespace, so I'm not sure your explanation makes sense.  Have you invoked the script with debug logging enabled?

```bash
bash -x ./scripts/delete-federation.sh
```

**Comment by danehans** [comment]
kubectl was trying to delete the resources in the default namespace. Because the `--ignore-not-found=true` flag is being passed, no errors are thrown. The resources are being created in namespace `federation-system`. When I tried the portion of [code](https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/delete-federation.sh#L43-L46) from the deletion script, the resources continued to exist in the `federation-system` ns. When I manually invoked the code with my proposed fix, it worked:
```
$ KCD="kubectl --ignore-not-found=true delete"
$ NS=federation-system
$ for filename in ./config/federatedtypes/*.yaml; do
  ${KCD} -f "${filename}" ${NS}
done
```

**Comment by gyliu513** [comment]
yes, we should have namespace for federeatedtype now, as this resource is also namespace scoped now https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/deploy-federation.sh#L142

```
# Enable available types
for filename in ./config/federatedtypes/*.yaml; do
  kubectl -n "${NS}" apply -f "${filename}"
done
```

**Comment by marun** [comment]
@danehans I get that the resources were not being deleted.  My question was regarding your report of the script hanging, which I don't believe is related to the problem you are fixing.

**Comment by danehans** [comment]
@marun I can give the delete script another try. It just sat there idle for a couple minutes until I decided to ctrl-C.

**Comment by marun** [comment]
@danehans Any update on this issue?

**Comment by danehans** [comment]
@marun I just tested and it works. I'll close the issue. Thank you.
