### ISSUE TITLE
User Guide example fails

### ISSUE THREAD

**Issue by onyiny-ang** [kubernetes-sigs/federation-v2#232]
When trying to run through the federation-v2 tutorial using the suggested minikube CI build, the status of resources (from this point onward: https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#check-status-of-resources) does not appear to exist in any of the clusters. The only thing that does appear in the first `get` call is:
```
------------ cluster1 ------------

NAME                  TYPE                                  DATA      AGE
default-token-wfkzm   kubernetes.io/service-account-token   3         26m
```

**Comment by tuminoid** [comment]
Getting same result with non-minikube clusters too running k8s `1.11.2`.

**Comment by font** [comment]
I've identified the root cause of this and will be opening up a PR with a fix soon.
