### ISSUE TITLE
Strategy for deploying specific versions and ensuring instructions against master stay working

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#241]
In the federation WG today we discussed how to prevent #232 from recurring, and arrived at the following consensus:

- There should be a way to deploy a specific version of federation that we capture for each version
- There should be a CI test that ensures that the development instructions work against the `master` branch

We decided to address this as follows:

- Make `install-latest.yaml` work again with the current `latest` tagged image (which corresponds to 0.0.1) (#239) 
- As a short-term tactical fix, add a yaml that represents the installation of the latest _unreleased_ version - that is, the master branch
- We should move toward a helm chart that is versioned according to the released version of federation that it installs - ie, chart version 0.0.1 installs federation 0.0.1
- We should publish this chart to a chart repository as part of the release process when we release a new version of federation

I've created this issue to document the group's concensus - please comment if you feel something was missed or inaccurate in this issue.

**Comment by pmorie** [comment]
@gyliu513 has opened a pull request to add the federation v2 chart to the official helm charts repo:

https://github.com/helm/charts/pull/8631

**Comment by pmorie** [comment]
Per our discussion on the October 17th WG meeting, releasing the chart will be a post-release step once the image builds are complete and the github release is tagged.

**Comment by marun** [comment]
@gyliu513 It looks like the pull to add to the helm repo was closed.  Would you be willing to revisit? Ideally we would be publishing a new release of the chart to the official repo with every release of federation (and ensure the chart defaults to the appropriate image version instead of master's use of `canary`).

**Comment by marun** [comment]
I think this issue has been superceded by #701.
