### ISSUE TITLE
Consider UX when federating cluster scoped objects

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/federation-v2#242]
We need to consider the UX when dealing with cluster-scoped objects that we would like to federate. That is, for a cluster-scoped `Foo` type that we would like to federate, do we create a respective `FederatedFoo` type or just rely on creating `Foo` objects in the host cluster in order to federate them?

For example, today we support federating the `Namespace` resource and because of the UX as well as it being cluster-scoped, we do not have a `FederatedNamespace` type. Instead, we rely on the user creating namespaces in the host cluster in order to federate the namespace. The UX looks like this:

```bash
# On the host cluster
kubectl create ns test-namespace
kubectl -n test-namespace create federatednamespaceplacement ...
# test-namespace is synced to clusters selected for placement
```

If there were a `FederatedNamespace` API type, it would have to also be cluster-scoped and the UX might look like the following:

```bash
# On the host cluster
kubectl create federatednamespace test-namespace
# federatednamespace sync controller would create test-namespace. Once test-namespace
# is created:
kubectl -n test-namespace create federatednamespaceplacement ...
# test-namespace is synced to clusters selected for placement
```

Which is preferable for namespaces?

We should also consider the UX for other cluster-scoped resources that we *may* want to federate:

- ClusterRole
- ClusterRoleBinding
- InitializerConfiguration
- ValidatingWebhookConfiguration
- MutatingWebhookConfiguration
- PodSecurityPolicy
- APIService
- any custom CRD whose CRs are cluster-scoped
- etc.

Do we follow precedence for these or any other cluster-scoped resources as is done for namespaces? Or implement a corresponding `Federated<TYPE>` resource? If the latter, do we make it cluster-scoped or namespace-scoped?

**Comment by danehans** [comment]
I prefer option 2:
```
# On the host cluster
kubectl create federatednamespace test-namespace
# federatednamespace sync controller would create test-namespace. Once test-namespace
# is created:
kubectl -n test-namespace create federatednamespaceplacement ...
# test-namespace is synced to clusters selected for placement
```
It keeps the UX of creating cluster-scoped resources consistent with namespace-scoped resources. With that said, I would like to see the `FederatedNamespace` follow this approach. As a new contributor, it was easy to pick-up how namespace-scoped resources are federated.

What happens if I do not want the cluster-scoped resource created in the host cluster? I have to create the resource in the host cluster and then remove it in the associated `Placement` resource?

**Comment by gyliu513** [comment]
@danehans , If you delete the federated resource from host cluster, then all of the resources in member cluster will be deleted, please check https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/controller/util/deletionhelper/deletion_helper.go#L35-L44 . And currently, the finalizer will always be added to all federated resources.

For the solution, seems option 1) may be better? As this will not request any CRD `Federated<TYPE>` resources, and customer only need to create a `placement` to decide where to propagate the resources.

One more thing, seems we need to rename the `FederatedNamespacePlacement` to `FederatedClusterResourcePlacement`, as all of the cluster-level resources can share one placement CRD resource.

**Comment by danehans** [comment]
> If you delete the federated resource from host cluster, then all of the resources in member cluster will be deleted

@gyliu513 I think that explains a shortcoming of the existing approach, the resource must exist in the host cluster even if the resource is not needed in that cluster. This is one of the reasons why I like option 2. As I mentioned above, I also like the consistent UX, even if it requires a user to create a `Federated<TYPE>` resource. The additional step is worth the consistent UX.

**Comment by marun** [comment]
`Namespace` does not have a `FederatedNamespace` equivalent due to it being the only container in the kube api.  The fact that it is cluster-scoped is incidental.  Any other resource - cluster-scoped or no - implies a `Federated<type>` template.   

Why is this the case?  If `FederatedNamespace` were a thing, and were cluster-scoped, it would not be able to contain resources to be federated (only namespaces can contain other resources).  A namespace of the same name would have to exist to contain those resources.  To avoid this complication, namespace federation is special-cased to depend only on `Namespace` and not `FederatedNamespace`.

**Comment by marun** [comment]
@gyliu513 Placement resources are per-type to ensure that there is always a direct correlation between the placement resource and its template equivalent (they have the same name).  Using a common type would require imposing a naming scheme on the user (e.g. <type>-<name>) which is arguably more complicated UX than using per-type placement types.

**Comment by marun** [comment]
@danehans The only case where a resource must exist in the host cluster to be federated is for namespaces.  This is a function of namespaces being the only container.  Every other cluster-scoped type implies a `Federated<type>` template and does not require that the target type ever exist in the host cluster.

**Comment by marun** [comment]
@font I think the scope of a `Federated<type>` template should correspond to the scope of the resource it is targeting.

**Comment by danehans** [comment]
@marun thank you for the explanation. I will proceed with adding cluster-scoped types (i.e. `ClusterRole`) by implementing the equivalent `Federated<type>`.

**Comment by font** [comment]
@marun That would probably be my preference as well, including the placement and overrides, but left it open for discussion to see what others think.

**Comment by gyliu513** [comment]
Using `Federated<type>` will cause if there are new cluster-scope resources added in Kubernetes and want to be added to federation v2, then we will always need to define the API and CRD for `Federated<type>`, this will bring some effort for maintain, and also the only concern from me.

But agree that keeping consistent UX for all federated resources is good for end users, so +1 to have `Federated<type>`.

Another question is for CRD, I think we may need to define a `federatedCRD` and use this resource type to handle all CRD resources across clusters?

@marun I still have one question for `FederatedNamespacePlacement`, did not quite catch your point. But my thinking is suppose I have two cluster-scope resources want to be deployed, if we have `FederatedClusterResourcePlacement`, then I can define the placement YAML as follows for different resources:

Create `test-namespace1` to `cluster1` and `cluster2` with `FederatedClusterResourcePlacement`.
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace1
```
```
apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedClusterResourcePlacement
  metadata:
    name: test-namespace1
  spec:
    clusternames:
    - cluster1
    - cluster2
```

Create `test-namespace2` to `cluster1` and `cluster2` with `FederatedClusterResourcePlacement`.
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace2
```
```
apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedClusterResourcePlacement
  metadata:
    name: test-namespace2
  spec:
    clusternames:
    - cluster1
    - cluster2
```

What is the problem for a common `FederatedClusterResourcePlacement`?

**Comment by marun** [comment]
@gyliu513 Type-specific placement has direct associativity - a placement resource named `foo` defines configuration for a federated type named `foo`.

How would a controller determine which federated resource the `FederatedClusterResourcePlacement` should target?  If the placement resource is not type-specific, a name is not sufficient.

**Comment by gyliu513** [comment]
@marun I see, with current design, each `placement` need to bind to a `type`.

But I'm wondering why each `type` need a `placement` object? As I can see for federation, the `placement` actually defines in which cluster I want to create my resources, it is a common operation for all federation resources. So is it possible that we abstract out the `placement` and create one `placement` object for all federation resources.

**Comment by marun** [comment]
Given that federation of cluster-scoped types is now implemented, I think this issue is no longer actionable.
