### ISSUE TITLE
Consider refining API group structure

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#256]
We currently have a single API group (`core.federation.k8s.io`) that has multiple conceptual areas bound up in it:

1. `FederatedCluster` and `FederatedTypeConfig` which program federation with the set of clusters to target and API types to spread, respectively
2. The types for the federation API for the k8s core - `FederatedDeployment`, etc

It seems to me like area (1) is distinct logically from area (2); area (1) is intrinsic to the federation mechanisms while area (2) is an application of area (1) for parts of the kubernetes API. Area (1) is also largely a function of push propagation; another propagation mechanism may be configured in a different way entirely but may use the resources from area (2). For these reasons I think we should consider separating these two areas into distinct API groups:

- `push.federation.k8s.io` for area (1)
- `kubernetes.federation.k8s.io` for area (2)

Note, names are just suggestions. Also note that I think if we decided to do this that the benefit would be more around clarifying understanding of what we're building in federation (at this point) than a clear technological advantage - it would compliment our story for federation being 'building blocks' rather than a monolith.

**Comment by gyliu513** [comment]
> Area (1) is also largely a function of push propagation; another propagation mechanism may be configured in a different way entirely but may use the resources from area (2).

Not quite clear for why does the Area (1) is for push propagation? I think even with pull mode, we still need Area (1). As the pull mode still need to check the cluster resources, the federated resource types.

Also seems the `FederatedTypeConfig` also belong to `core`, as it manages all federated resource types.

**Comment by marun** [comment]
I agree with @gyliu513 that (1) could be used for both push and pull propagation.

I'm not sure about `kubernetes.federation.k8s.io` in the context of generating primitives.  Should  primitives for 3rd party api types (including crds) end up in that group too, or in a new group?  Or would it make sense to use an agnostic name (e.g. `primitives.federation.k8s.io`)?

**Comment by gyliu513** [comment]
@marun @pmorie 

More thinking about this topic based on @marun 's append.

- Area (1) including `FederatedCluster` and `FederatedTypeConfig` continue use `core.federation.k8s.io`.
- +1 to @marun for Area (2) using `primitives.federation.k8s.io`. For `kubernetes.federation.k8s.io`, it seems a bit duplicate, as `kubernetes` and `k8s` are actually same.

So the proposal is:

- core.federation.k8s.io for area (1)
- primitives.federation.k8s.io for area (2)

**Comment by marun** [comment]
With #426 having merged, the proposal has been implemented:

- core.federation.k8s.io for area (1)
- primitives.federation.k8s.io for area (2)
