### ISSUE TITLE
Consider renaming 'sync' controller

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#258]
Currently, this repo implements a 'push' reconciliation mechanism with the 'sync' controller. The name 'sync controller' is fairly ambiguous - we should consider renaming this controller to the 'push controller' or 'push propagation controller', possibly in connection with renames of API groups in #256

**Comment by gyliu513** [comment]
+1 to rename it to `push propagation controller`.

**Comment by marun** [comment]
Do we need the `controller` suffix?  How about:

- `push propagator`
- `push reconciler`

**Comment by gyliu513** [comment]
I prefer that we add the `controller` suffix to keep consistent with Kubernetes.

![image](https://user-images.githubusercontent.com/4461983/45464688-4d756b00-b744-11e8-96b0-174ceef4832d.png)

So here my proposal is rename the folder of `sync` to `pushpropagator`, and the file name of the controller is `pushpropagator_controller.go`.

```
// PushPropagatorController synchronizes the state of a federated type
// to clusters that are members of the federation.
type PushPropagatorController struct {
}
```

```
// newPushPropagatorController returns a new push propagator controller for the configuration
func newPushPropagatorController(typeConfig typeconfig.Interface, kubeConfig *restclient.Config, fedNamespace, clusterNamespace, targetNamespace string) (*FederationSyncController, error) {
}
```

Besides, I also found that we are not using consistent names for all of the controllers, take a look at the picture as below. How about follow the guidance proposed above and rename all of the controllers and its related variables?

![image](https://user-images.githubusercontent.com/4461983/45464628-17d08200-b744-11e8-81bc-da950a2881a1.png)

@marun @pmorie comments?

**Comment by gyliu513** [comment]
Using different names for the file name of the `controllers` can also help to improve the debug-ability, as the logs will include the file name, all controllers using name of `controller.go` sometimes difficult to debug or else if I want to grep logs for a specified controller.

**Comment by marun** [comment]
I think the way logs only provide the name of the file is a pretty big flaw in golang logging, and I think it's worth considering how to get more context rather than a bandaid solution like unique file naming since that doesn't help if logging originates from 3rd party dependencies.

**Comment by marun** [comment]
I also think consistent naming of controllers is a pretty low priority.  End-user functionality is our ultimate responsibility, and I don't think enforcing an arbitrary file naming scheme buys us much in that regard.  Also, what makes sense for Kubernetes in terms of code structure doesn't necessary make sense for us - it is a huge and monolithic legacy project.

**Comment by gyliu513** [comment]
@marun I recalled that Kubernetes community has some discussion for this, but I cannot find the discussion now, just post a question in kubernetes-dev https://groups.google.com/forum/#!topic/kubernetes-dev/23s6MTTt3gU and we can get some comments from there.

But here I want to control the scope of the discussion to this issue, any comments for my proposal?

Rename the folder of `sync` to `pushpropagator`, and the file name of the controller is `pushpropagator_controller.go`.

```
// PushPropagatorController synchronizes the state of a federated type
// to clusters that are members of the federation.
type PushPropagatorController struct {
}
```

```
// newPushPropagatorController returns a new push propagator controller for the configuration
func newPushPropagatorController(typeConfig typeconfig.Interface, kubeConfig *restclient.Config, fedNamespace, clusterNamespace, targetNamespace string) (*FederationSyncController, error) {
}
```

**Comment by marun** [comment]
I don't think we're any closer to renaming the sync controller than we were in September.  It just doesn't seem like much of a priority (especially in the absence of pull reconciliation).  I'm closing for now, and we can revisit in the future if necessary.
