### ISSUE TITLE
Add more examples for 0.0.2 release

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#262]
Follow-up from September 12 working group meeting.

In the coming 0.0.2 release, we introduced some new features for federation v2 but we do not have examples for those new features, it is better add examples for those features for end user to have a try for the new features.

Some features in my mind is as follows:
- Replica Scheduling Preference
- Job Scheduling Preference
- Federated Ingress
- Federated Jobs
- ...

@irfanurrehman @marun @kubernetes-sigs/federation-wg

**Comment by gyliu513** [comment]
@shashidharatd would you please add a test example for federated ingress?

@irfanurrehman as you are working for Job Scheduling at https://github.com/kubernetes-sigs/federation-v2/pull/259 , I assume you will add example for this ;-)

**Comment by marun** [comment]
@gyliu513 Given that 0.0.2 was released some time ago, I'm closing this issue.  Please file a separate issue for a future release if there are outstanding doc requirements not captured elsewhere.

**Comment by gyliu513** [comment]
@marun all of the examples are now there and it is ok to close this.
