### ISSUE TITLE
Namespace sync controller is run when --limited-scope=true

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/federation-v2#297]
With `--limited-scope=true` (namespace-scoped deployment) the federation control plane operates on a single namespace. As a result, the `Namespace` sync controller is not necessary as the creation and deletion of the namespace is not up to the federation controller, nor does it have the permissions necessary for it. There is a check for this in the testing code, but a check needs to be added to the main path.

**Comment by gyliu513** [comment]
@font I think we can close this one as namespace sync controller will not run after PR #299

**Comment by font** [comment]
Fixed by #299.
