### ISSUE TITLE
Ability to create or remove all resources in namespace with namespace-scoped deployment

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/federation-v2#298]
With a cluster-scoped federation control plane deployment, we currently support creation and removal of all resources in a namespace by creating or deleting the entire namespace in target clusters via `FederatedNamespacePlacement`. With a namespace-scoped deployment, the existence of a namespace is not up to the federation controller as we no longer have a `Namespace` sync controller (after #297 is fixed), nor does the federation controller have permissions to create/delete namespaces.

Even with those limitations, we need the ability to create or remove all resources in a namespace for namespace-scoped deployments as we have for cluster-scoped. The fix for #75 would be part of this.

**Comment by gyliu513** [comment]
@font I was a bit confused for this, for namespace-scoped federation, when I join a new cluster, the `kubefed2 join` will create the related namespace in the member cluster.

Then we can use `template`, `placement`, `override`, to sync up resources in the specified namespace, we can also remove resource from the specified cluster if we remove the cluster from `placement`.

If I remove all clusters from `placement`, does the resource can be deleted in all member clusters?

**Comment by font** [comment]
@gyliu513 While it is currently possible to remove all the resources in a namespace for namespace-scoped deployments by updating all placement resources, it is not possible to do it in the same way that we can do it with cluster-scoped deployments -- by just removing the cluster from the `federatednamespaceplacement` resource. This issue is to track the ability to remove *all* resources in a namespace using a similar UX as we have for cluster-scoped deployments.

**Comment by gyliu513** [comment]
Ah, I see, thanks @font . So this issue is that we still want to use `federatednamespaceplacement`, but for namespace-scoped federation, as we can only deploy resources in the namespace where federation controller is running, so when delete resources, we should also make sure that the `federationclusters` will not be deleted.

Will check @marun 's PR to see how it is fixing this, thanks.
