### ISSUE TITLE
Add missing go tools.

### ISSUE THREAD

**Issue by poothia** [kubernetes-sigs/federation-v2#302]
This issue is to track to have various go tools and their automated scripts.

/sig multicluster

**Comment by marun** [comment]
I'd like to see an explanation and discussion of why these go tools are necessary or desirable.   Is there a mandate to impose these tools from outside the sig, or some other rational you'd like to share?

**Comment by marun** [comment]
@poothia Can this issue be closed?

**Comment by poothia** [comment]
@marun I think it can be closed and individual issues can be opened to add missing go scripts checks, that would be more specific.
what do you think?
