### ISSUE TITLE
Use typeconfig to get resource definitions of known resources.

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/federation-v2#325]
The precedent is shown in this review commit [here](https://github.com/kubernetes-sigs/federation-v2/pull/259/commits/0757fb444aa81f3608aa5e7c8de8bb09e6734a06#r222386590) and implementation for one type in the review fixes [here](https://github.com/kubernetes-sigs/federation-v2/pull/259/commits/0757fb444aa81f3608aa5e7c8de8bb09e6734a06).
The same can be extended for other resource types (but not necessarily all) resources defined in https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/schedulingtypes/resources.go

**Comment by xunpan** [comment]
I can work on this.

**Comment by xunpan** [comment]
I finished the code diff with similar logic in Job implementation. But I found that it does not work properly if related FederatedTypeConfig resource is not initialized but federation controller initialized.

Currently, the implementation is to get resource from FederatedTypeConfig. E.g.
`fedClient.CoreV1alpha1().FederatedTypeConfigs(DefaultFederationSystemNamespace).Get("deployments.apps", metav1.GetOptions{})`
After that, the target APIResource of returned value is used in code logic.

However, based on steps in user guide. federation-controller-manager pod is created together with FederatedTypeConfig CRD in applying hack/install.yaml. 

after that, FederatedTypeConfig resources are created. If the controller pod is initialized before such resources creation, any getter functions will failed in getting FederatedTypeConfig resources.

I guess logics in "Simplified high level Job Scheduling #259" will not work for Job resources too.
@irfanurrehman , @gyliu513

**Comment by gyliu513** [comment]
@irfanurrehman @xunpan how about ignore this error and just return if the `FederatedTypeConfig resources` are not created?

**Comment by irfanurrehman** [comment]
@xunpan refer https://github.com/kubernetes-sigs/federation-v2/blob/02efddee7c013515820aa53ed4e9dc6e096a6923/test/integration/jobschedulingpreference_test.go#L98.
This is needed for integration.

**Comment by marun** [comment]
@irfanurrehman What was this in relation to?  The link in the issue post doesn't work for me.

**Comment by irfanurrehman** [comment]
> @irfanurrehman What was this in relation to? The link in the issue post doesn't work for me.

@marun this was in continuation to your [comment](https://github.com/kubernetes-sigs/federation-v2/pull/259#discussion_r222379655) on https://github.com/kubernetes-sigs/federation-v2/pull/259. This issue was created to do updates on similar lines for all (all possible) resource definitions in scheduling type controllers.

@xunpan I have created https://github.com/kubernetes-sigs/federation-v2/issues/349, which can ensure that this mechanism of getting resource definition will work, as the controller will run only if the target resource type config exists. Would you be interested in taking that up too?

**Comment by test0x1000** [comment]
@irfanurrehman OK. I will take it.

**Comment by xunpan** [comment]
@irfanurrehman I think we can close this issue because #366 is merged.
