### ISSUE TITLE
Unify some concept for federation V2

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#333]
This is a follow up action based on discussion on 2018.10.17 WG group meeting https://docs.google.com/document/d/1v-Kb1pUs3ww_x0MiKtgcyTXCAuZlbVlz4_A9wS3_HXY/edit#heading=h.m2zygcva2jq1

Some initial concepts proposal and thoughts are as following:

| Concept | Description | Notes|
|-----------|-------------|---------|
| **Federation** | Kubernetes Cluster Federation enables users to federate multiple Kubernetes clusters for resources sync up, service discovery, high availability etc across multiple clusters, it also helped to prevents cluster provider lock-in. | Federation is a subproject for Kubernetes multicluster. |
| **Host Cluster** | The cluster where federation controller running. We can have only one Host Cluster in a multicluster environment. | |
| **Member Cluster** | The cluster which is managed by federation controller. The Host Cluster can also be a Member Cluster. | |

@danehans I think you also want to add more nomenclature for Multi Cluster Ingress/Service DNS as well, can you help to update the table above by adding some content?

@pmorie @marun @font @irfanurrehman @shashidharatd @quinton-hoole-2 please show your comments if any. I want to use this ticket to trace the concepts that we want to add for federation v2, after we come to a conclusion, I will create a PR to add this into federation document.

**Comment by danehans** [comment]
IMO it's easier to work on the table if it were a goog sheet or doc. Here are the add'l concepts that I believe should be addressed:

| Type        | Description           | Notes  |
| ------------- |:-------------| -----:|
| MultiClusterServiceServiceRecord      | A resource that associates one or more Kubernetes `Service` resources and how to access the `Service`, with a scheme for constructing Domain Name System (DNS) [resource records](https://www.ietf.org/rfc/rfc1035.txt) for the `Service`.| |
| MultiClusterIngressDNSRecord      | A resource that associates one or more Kubernetes `Ingress` and how to access the `Ingress` resources, with a scheme for constructing Domain Name System (DNS) [resource records](https://www.ietf.org/rfc/rfc1035.txt) for the `Ingress`.|  |
|  DNSEndpoint     | Is a [`Custom Resource`](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) wrapper for the `Endpoint` resource.|  |
|  Endpoint     | A resource that represents a Domain Name System (DNS) [resource record](https://www.ietf.org/rfc/rfc1035.txt).  |  |

**Comment by gyliu513** [comment]
Good suggestion @danehans , I created a google doc here https://docs.google.com/document/d/1LD-iIhzW2a-NzbNK5WLKrKhILrg21AeF1JpXkcYECtg/edit?usp=sharing , we can iterate on this document for the concepts.
