### ISSUE TITLE
Refactor ServiceDNSRecord API

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes-sigs/federation-v2#348]
Currently, the `ServiceDNSRecord` API is as below
```
type ServiceDNSRecordSpec struct {
	// FederationName is the name of the federation to which the corresponding federated service belongs
	FederationName string `json:"federationName,omitempty"`
	// DNSSuffix is the suffix (domain) to append to DNS names
	DNSSuffix string `json:"dnsSuffix,omitempty"`
	// RecordTTL is the TTL in seconds for DNS records created for this Service, if omitted a default would be used
	RecordTTL TTL `json:"recordTTL,omitempty"`
}
```

There is little ambiguity and it is also prone to errors by user's input, and we don't have validation mechanism in place. Logically one federation should be associated with one domain name, but there is no way to enforce it in the current API. (Like for e.g. user can create multiple `ServiceDNSRecords` with the same `FederationName` but with different `DNSSuffix`). So i suggest a slight improvement in API to maintain the `FederationName` to domain mapping in a separate API. like below

```
type FederationDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// FederationDomain is the DNS zone associated with the federation
	FederationDomain string `json:"federationDomain"`
	// Authoritative DNS Name Server for the federation domain
	NameServer string `json:nameServer,omitempty"`
}
```

`FederationDomain` would be a ~~cluster-scoped object~~(object in federation system namespace, similar to federated cluster) with the name, representing the federation. It would also serve as single source of truth for federation to domain mapping. it can also be used to configure in-cluster DNS to fallback/forward to the configured nameserver when federation name lookup happens. `NameServer` is optional and when omitted federation name lookup happens with public namesaervers.

The `ServiceDNSRecordSpec` would not contain the `DNSSuffix` and instead would contain just the `FederationName`. A federated service should belong to one federation, however there could be multiple federations in the system.

A `FederationDomain` has to be defined first before using it in `ServiceDNSRecordSpec`. We shall add validation admission controller in future to validate `FederationDomain` exist before creating a `ServiceDNSRecordSpec` referring the federation name.

There is also 2 other requirements https://github.com/kubernetes-sigs/federation-v2/issues/330 and https://github.com/kubernetes-sigs/federation-v2/issues/329, so i would suggest the following refactoring for the ServiceDNSRecord API:
```
type ServiceDNSRecordSpec struct {
	// FederationName is the name of the federation to which the corresponding federated service belongs
	FederationName string `json:"federationName,omitempty"`
	// RecordTTL is the TTL in seconds for DNS records created for this Service, if omitted a default would be used
	RecordTTL TTL `json:"recordTTL,omitempty"`
	// DNSPrefix when specified, an additional DNS record would be created with <DNSPrefix>.<FederationDomain>
	DNSPrefix string `json:"dnsPrefix,omitempty"`
	// AllowServiceWithoutEndpoints allows DNS records to be written for Service shards without endpoints
	AllowServiceWithoutEndpoints bool `json:"allowServiceWithoutEndpoints,omitempty"`
}

type ServiceDNSRecordStatus struct {
	// Domain for the Federation as observed by the controller from FederationDomain Map
	Domain string `json:"domain,omitempty"`
        // Per cluster DNS data for the service
	DNS []ClusterDNS `json:"dns,omitempty"`
}
```

request for your comments
/cc @danehans @quinton-hoole @pmorie @font @marun

**Comment by font** [comment]
@shashidharatd Thanks for creating this issue! I have some comments below.

> Logically one federation should be associated with one domain name, but there is no way to enforce it in the current API. (Like for e.g. user can create multiple ServiceDNSRecords with the same FederationName but with different DNSSuffix).

By "one federation" I presume you mean one federation deployment. If that's the case, I think the current mechanism enables the use of multiple sub-domains so that each `ServiceDNSRecord` can be associated with a different `DNSSuffix` e.g. `foo.example.com` and `bar.example.com`. With these changes it would mean you can only have one domain mapping to one federation, so only `example.com`. This prevents the ability for users to divide up their domain and services however they see fit.

> FederationDomain would be a ~~cluster-scoped object~~(object in federation system namespace, similar to federated cluster) with the name, representing the federation. It would also serve as single source of truth for federation to domain mapping. it can also be used to configure in-cluster DNS to fallback/forward to the configured nameserver when federation name lookup happens. NameServer is optional and when omitted federation name lookup happens with public namesaervers.

It seems like the `NameServer` option would be most useful for somebody to specify their own non-public nameserver that resides outside of their cluster. Otherwise, if you want local-in-cluster DNS resolution for federation name lookups via `kube-dns`, I imagine that would automatically happen if using something like `CoreDNS`, albeit with the `federation` plugin enabled. Also, what would actually program `kube-dns` to perform this action?

I'm not sure how these changes are addressing #329. Could you clarify?

**Comment by shashidharatd** [comment]
> By "one federation" I presume you mean one federation deployment. If that's the case, I think the current mechanism enables the use of multiple sub-domains so that each ServiceDNSRecord can be associated with a different DNSSuffix e.g. foo.example.com and bar.example.com. With these changes it would mean you can only have one domain mapping to one federation, so only example.com. This prevents the ability for users to divide up their domain and services however they see fit.

federation in the context of this features is logical grouping of federated services. I have created some slides related to this feature. https://docs.google.com/presentation/d/1b6yI3FpysxvdLvCmrR5sgIeDcG7nMGdG3b169sed-pY/edit#slide=id.p hope it clarifies some internal workings of this feature.

> I'm not sure how these changes are addressing #329. Could you clarify?

This pr partially addresses #329, to configure additional DNS name for federated service, which will be useful for external clients (outside k8s clusters), who think the name is quite long and cumbersome.

**Comment by danehans** [comment]
@shashidharatd Thanks for creating the issue and slides. I provided feedback in the slides.

**Comment by danehans** [comment]
@shashidharatd what else is needed to close this issue?
