### ISSUE TITLE
Make RSP clusterUnavailableDelay and clusterAvailableDelay configurable

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#356]
Now, when I enable RSP, if I did a test with the rebalance feature. After deploying on two clusters, I deliberately brought down one of the clusters, then I need to wait at least 1min for all of my pods balanced to the running cluster, it is better to make the clusterUnavailableDelay/clusterAvailableDelay configurable, so that customer can configure those values based on their cluster scale.

Please refer to https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/controller/schedulingpreference/controller.go#L99 for the hard-code clusterUnavailableDelay and clusterAvailableDelay.

/cc @irfanurrehman can you please add `good-first-issue` for this issue? Thanks.

**Comment by tghartland** [comment]
I could try this.

Should the delay should be configurable per RSP (as in a property added [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/hack/install-latest.yaml#L1384)) or is it a single property of the entire multicluster? I'm not sure exactly how and where it is that controller/schedulingpreference is running, is it a continuous part of the cluster itself or is it just run during the initial setup?

**Comment by gyliu513** [comment]
Thanks @tghartland for the help.

Here are some of my thinking, as we have only one RSP controller for the whole federation cluster, so I think this value should be a global value. We may need to add some parameters at https://github.com/kubernetes-sigs/federation-v2/blob/master/cmd/controller-manager/main.go#L114 to define clusterUnavailableDelay and clusterAvailableDelay.

@irfanurrehman WDYT? Thanks.

**Comment by tghartland** [comment]
Ah, so the delays will be defined as arguments [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/hack/install-latest.yaml#L1451) and then passed through controller-manager/main.go to the RSP controller at the line you linked.
I think I have enough information to start working on this now, I'll let you know when I run into problems.

**Comment by irfanurrehman** [comment]
> Ah, so the delays will be defined as arguments [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/hack/install-latest.yaml#L1451) and then passed through controller-manager/main.go to the RSP controller at the line you linked.
> I think I have enough information to start working on this now, I'll let you know when I run into problems.

You are right. Meanwhile the argument names should be quite specific, such that any other controller (within controller manager) needing similar configurations can be given clear disambiguation.
Also, as a future enhancement you can also look at a component config to handle the various controller arguments.

**Comment by tghartland** [comment]
I have added some placeholder flags. I copied the format from the flags that were already there, including the "If unset...", but when the help is printed it already prints the default value in brackets. Is that unintended, or is it duplicated just to specifically say that the flag is optional?
```
$ docker run thartland/federation-v2:test --help
Usage of ./controller-manager:
.........
  -registry-namespace string
        The cluster registry namespace.  If unset, will default to "kube-multicluster-public". (default "kube-multicluster-public")
  -rsp-available-delay int
        Time to wait before scheduling on a newly healthy cluster. If unset, will default to 20. (default 20)
  -rsp-unavailable-delay int
        Time to wait before giving up on an unhealthy cluster. If unset, will default to 60. (default 60)
.........
```
I would also be happy to have your input on the flag name and the usage text. From your description I think I have mostly figured out what the flags do but you can probably describe it better than I can.

I have written the available delay usage text assuming that the delay only applies to clusters that transition from unhealthy -> healthy, does it also apply to brand new clusters added to the multicluster?

**Comment by gyliu513** [comment]
@tghartland for the first issue

```
$ docker run thartland/federation-v2:test --help
Usage of ./controller-manager:
.........
  -registry-namespace string
        The cluster registry namespace.  If unset, will default to "kube-multicluster-public". (default "kube-multicluster-public")
  -rsp-available-delay int
        Time to wait before scheduling on a newly healthy cluster. If unset, will default to 20. (default 20)
  -rsp-unavailable-delay int
        Time to wait before giving up on an unhealthy cluster. If unset, will default to 60. (default 60)
.........
```
I think it is a bug, the go `flag` already can help print out the default value, so I think we can remove the sentence like `If unset, will default to`. 

> I would also be happy to have your input on the flag name and the usage text. From your description I think I have mostly figured out what the flags do but you can probably describe it better than I can.

The help message lgtm, but I think @irfanurrehman can provide more comments for this.

> I have written the available delay usage text assuming that the delay only applies to clusters that transition from unhealthy -> healthy, does it also apply to brand new clusters added to the multicluster?

Yes, it will also apply to new clusters added to as well as clusters removed from the multicluster.

@irfanurrehman please show your comments if any, thanks.

**Comment by tghartland** [comment]
I now have the command line values being passed through to where they are used. I had to add a flag --rsp-minimize-latency as well since that was always true before and would override the new values. I have left the default of that as true to preserve the current behaviour.

I'm thinking about input validation, and if the provided value is a negative integer is it better to just error and quit or to revert to default values? Or considering how the value is used would it just be treated as 0 anyway i.e if you're checking `current_time > start_time + delay`?

**Comment by irfanurrehman** [comment]
@tghartland the minimize latency value set to `true` [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/cmd/controller-manager/main.go#L114) seems to be a mistake. It should be set to `false`. The function minimize latency is only for use in tests.

I checked the code further and found that `clusterAvailableDelay`, and `clusterUnavailableDelay` are used in `SchedulingPreference Controller`, `servicedns controller` and `ingressdns controller`, with common timeouts at all places. I think we can use common controller params, for now, in all three. So you can do away with adding 2 params named as below (and values set into all three controllers):
1. cluster-available-delay - Time to wait before reconciling on a newly healthy cluster
2. cluster-unavailable-delay - Time to wait before giving up on an unhealthy cluster

cc @shashidharatd

**Comment by marinoborges** [comment]
I have 2 questions regarding this topic: 
1. If I edit a KubeFedConfig resource for one cluster, specifically the `spec.controllerDuration.unavailableDelay` field, this setting takes effect immediately or a restart in the kubefed-controller-manager pod is needed?
2. Do I need to edit this field for all the clusters in the federation individually?
