### ISSUE TITLE
Manifest Conversion Tool

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#362]
Converting Kubernetes manifests to a "Federated" equivalent is time consuming, error prone and can be a barrier to adopting federation-v2. For example, Istio consists of 100+ Kubernetes resources that has become burdensome to Federate. I suggest adding a command (i.e. `render`, `convert`, etc.) to `kubefed2` that takes a manifest consisting of one or more resources (using `---` as a resource separator) as input and generates the Federated equivalent file.

**Comment by danehans** [comment]
@marun thanks for the input. Please link your upcoming PR to this issue for tracking purposes. It has been very painful converting the Istio [v0.8 manifest](https://raw.githubusercontent.com/danehans/fedv2-manifests/master/istio/v0.8.0/src/istio.yaml) to its federated equivalent. A tool as proposed by this issue will go a long way to increasing adoption of federation-v2.

**Comment by marun** [comment]
This issue has been superceded by #477.
