### ISSUE TITLE
Add Cross Compile Support to Deploy Script

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#373]
The deployment [script](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/development.md#automated-deployment) builds the controller-manager bin using GOOS=darwin when running on Mac OSX. This causes problems because the Docker image uses the bin as darwin instead of linux.

**Comment by gyliu513** [comment]
@danehans can you please show more detail for where is using `GOOS=darwin`? I did not found it in the [script](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/development.md#automated-deployment) you mentioned, am I missing anything?

**Comment by gyliu513** [comment]
Does it because Kubernetes also support running on OSX?

**Comment by gyliu513** [comment]
FYI @xunpan

**Comment by gyliu513** [comment]
@danehans can you help close this one as it was resolved in https://github.com/kubernetes-sigs/federation-v2/pull/416

**Comment by gyliu513** [comment]
@danehans @shashidharatd do we also need to make the `kubefed2` also as cross compile? I found that both `controller-manager` and `hyperfed` support this but `kubefed2` not.

**Comment by marun** [comment]
I think we may want to add a darwin binary to the release artifacts for v1beta1.

**Comment by shashidharatd** [comment]
I can work on this if nobody else is working on this.

**Comment by shashidharatd** [comment]
@yamt, @draveness any of you interested in picking up this task?

**Comment by draveness** [comment]
> @yamt, @draveness any of you interested in picking up this task?

I could pick this up. :)

**Comment by draveness** [comment]
> I think we may want to add a darwin binary to the release artifacts for v1beta1.

Hi, just found out this PR https://github.com/kubernetes-sigs/federation-v2/pull/854/files#diff-935529b9829971ac67b10793cc76e3acR40 which build release artifacts automatically.

Is it correct we should use `kubefedctl-darwin` instead of `kubefedctl-linux`?

**Comment by marun** [comment]
@draveness `make kubefedctl` should continue building for the detected platform.  The cross compile support requested by this issue requires something like `make kubefedctl HOST_OS=<darwin|linux>` to enable building for a host os different from the one that the command is being executed on.

**Comment by marun** [comment]
@draveness Ideally the proposed build script would be able to automatically build `kubefectl` for both darwin and linux:

https://github.com/kubernetes-sigs/federation-v2/pull/854/files#diff-935529b9829971ac67b10793cc76e3acR37

**Comment by draveness** [comment]
> @draveness Ideally the proposed build script would be able to automatically build `kubefectl` for both darwin and linux:

Yeah, I ran this cmd on my laptop and got two binaries at the same time.

**Comment by draveness** [comment]
Sorry for questions again, does this script already have the ability to build binary cross platform, I ran the following cmd on macOS terminal:

```go
$ make kubefedctl HOST_OS=linux
mkdir -p bin
docker run --rm -v /Users/draveness/go/src/github.com/kubernetes-sigs/federation-v2:/go/src/github.com/kubernetes-sigs/federation-v2 -w /go/src/github.com/kubernetes-sigs/federation-v2 golang:1.11.2 /bin/sh -c 'GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build  -ldflags "-X github.com/kubernetes-sigs/federation-v2/pkg/version.version=v0.0.8-183-gd121d514 -X github.com/kubernetes-sigs/federation-v2/pkg/version.gitCommit=d121d51434e6095decfccd842429598d13fa0aac -X github.com/kubernetes-sigs/federation-v2/pkg/version.gitTreeState="clean" -X github.com/kubernetes-sigs/federation-v2/pkg/version.buildDate=2019-05-08T01:44:20Z" -o  bin/kubefedctl-linux cmd/kubefedctl/main.go'
ln -sf kubefedctl-linux bin/kubefedctl

$ bin/kubefedctl-linux
zsh: exec format error: bin/kubefedctl-linux

$ make kubefedctl HOST_OS=darwin
mkdir -p bin
docker run --rm -v /Users/draveness/go/src/github.com/kubernetes-sigs/federation-v2:/go/src/github.com/kubernetes-sigs/federation-v2 -w /go/src/github.com/kubernetes-sigs/federation-v2 golang:1.11.2 /bin/sh -c 'GOARCH=amd64 GOOS=darwin CGO_ENABLED=0 go build  -ldflags "-X github.com/kubernetes-sigs/federation-v2/pkg/version.version=v0.0.8-183-gd121d514 -X github.com/kubernetes-sigs/federation-v2/pkg/version.gitCommit=d121d51434e6095decfccd842429598d13fa0aac -X github.com/kubernetes-sigs/federation-v2/pkg/version.gitTreeState="clean" -X github.com/kubernetes-sigs/federation-v2/pkg/version.buildDate=2019-05-08T01:47:59Z" -o  bin/kubefedctl-darwin cmd/kubefedctl/main.go'
ln -sf kubefedctl-darwin bin/kubefedctl

$ ./bin/kubefedctl-darwin
kubefedctl controls a Kubernetes Cluster Federation. Find more information at https://github.com/kubernetes-sigs/federation-v2.
....
```

**Comment by marun** [comment]
I guess that would  be it, yes.  I can update the PR in question...

**Comment by marun** [comment]
I'm going to close this issue - it looks like it's fixed (thanks to @yamt).
