### ISSUE TITLE
Documentation for kubefed2 federate

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/federation-v2#383]
`kubefed2 federated` introduces useful functionality of generating CDR primitives for a given k8s type on the fly. It might however be a little overwhelming for an user to understand the whole functionality and interworking with the k8s cluster and federation control plane.
A documentation elaborating the bits and pieces and nuances of the same would be useful.

For anybody picking up this issue, the functionality was added by https://github.com/kubernetes-sigs/federation-v2/pull/340.

**Comment by gyliu513** [comment]
@irfanurrehman @marun can you help close this issue as https://github.com/kubernetes-sigs/federation-v2/pull/503 and https://github.com/kubernetes-sigs/federation-v2/pull/521 already got merged.
