### ISSUE TITLE
stop scheduling controller if federatedtypeconfig resource is deleted from system

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/federation-v2#386]
In PR [366 ](https://github.com/kubernetes-sigs/federation-v2/pull/366), we implement basic functions to reconcile federatedtypeconfig for scheduling controller when the resource is created.

This ticket is used to trace related resource deletion case to make sure schedulingmanager works gracefully for all cases.

**Comment by marun** [comment]
I think both deletion and disabling (`enablePropagation: false`) for a scheduled type should result in the scheduler being stopped.
