### ISSUE TITLE
kubefed2 federate resource pluralization

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#457]
The command does not properly pluralize recouces that end in "y":
```
$ kubectl get federatedserviceentries
error: the server doesn't have a resource type "federatedserviceentries"
$ kubectl get serviceentries
NAME          AGE
httpbin-ext   8m
$ kubectl get federatedserviceentrys
NAME          AGE
httpbin-ext   8m
```

In the above example, you see `federatedserviceentrys` should be `federatedserviceentries`.

**Comment by marun** [comment]
The command doesn't do any pluralization, it only prefixes `federated`.  If you check the plural name of the target and I'll bet you'll see that it is `serviceentrys`.

**Comment by marun** [comment]
(Please close if my perspective is correct)

**Comment by danehans** [comment]
@marun The target is `serviceentries` and not `serviceentrys`. If the target was `serviceentrys`, that would be a problem b/c the proper and expected pluralization of `ServiceEntry` is `serviceentries`. Istio users are expecting `ServiceEntry` to be pluralized as `serviceentries`. See:
```
$ kubectl get serviceentrys
error: the server doesn't have a resource type "serviceentrys"
$ kubectl get serviceentries
NAME          AGE
httpbin-ext   50m
$ kubectl get serviceentries --context cluster2
NAME          AGE
httpbin-ext   50m
```

The federated equivilent:
```
$ kubectl get federatedserviceentrys
NAME          AGE
httpbin-ext   53m
$ kubectl get federatedserviceentries
error: the server doesn't have a resource type "federatedserviceentries"
```

You can see the incorrect pluralization in the api resources as well:
```
$ kubectl api-resources | grep ServiceEntry
serviceentries                                                 networking.istio.io                 true         ServiceEntry
federatedserviceentryplacements                                primitives.federation.k8s.io        true         FederatedServiceEntryPlacement
federatedserviceentrys                                         primitives.federation.k8s.io        true         FederatedServiceEntry
```

I am submitting a PR to fix this issue.

**Comment by sohankunkerkar** [comment]
I had similar kind of issues while trying to rename `servicedns` API type. It was doing `servicednss` instead of `servicednses`. I've created a PR in the controllers-tool repository to fix this issue.
https://github.com/kubernetes-sigs/controller-tools/pull/106/files
With this in place, we can define the resource name with the help of `+kubebuilder:resource:path=" servicednses"` annotation.
@marun @danehans
