### ISSUE TITLE
bug: too many API struct format error and test error

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes-sigs/federation-v2#471]
**Domain API error:**
see [this](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/apis/multiclusterdns/v1alpha1/domain_types.go#L36)

format error as follows(`just lack the '"' in the NameServer param`):
```
type Domain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Domain is the DNS zone associated with the federation
	Domain string `json:"domain"`
	// NameServer is the authoritative DNS name server for the federation domain
	NameServer string `json:nameServer,omitempty"`
}
```

**make test error:**
```
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:61:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:61:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:67:27: result.Items[0].Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:67:51: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:72:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:72:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
# github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1_test
pkg/apis/core/v1alpha1/federatedcluster_types_test.go:25:2: imported and not used: "github.com/kubernetes-sigs/federation-v2/pkg/controller/util"
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:61:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:61:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:67:27: result.Items[0].Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:67:51: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:72:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:72:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
# github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:32:6: FakeIngressDNSRecords redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:32:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:37:5: ingressdnsrecordsResource redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:37:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:39:5: ingressdnsrecordsKind redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:39:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:42:6: (*FakeIngressDNSRecords).Get redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:42:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:53:6: (*FakeIngressDNSRecords).List redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:53:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:75:6: (*FakeIngressDNSRecords).Watch redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:75:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:82:6: (*FakeIngressDNSRecords).Create redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:82:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:32:6: FakeServiceDNSRecords redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:32:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:37:5: servicednsrecordsResource redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:37:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:39:5: servicednsrecordsKind redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:39:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:82:6: too many errors
```

**Comment by magicwang-cn** [comment]
@marun @shashidharatd @pmorie 
currently,  ./script/pre-commit.sh does not do the UT test?

**Comment by marun** [comment]
No, there are no unit tests at present worth running.  The generated tests are useless, and should probably be removed.

**Comment by magicwang-cn** [comment]
oh, :(

but the currently pre-commit check is not enough, i think. like the `Domain API error`

**Comment by marun** [comment]
It's not that the precommit check isn't enough, it's that the e2e isn't comprehensive enough.  We're still in alpha, so the emphasis is on validating end-user functionality rather than doing comprehensive testing of functionality that may not live to see end-users.

**Comment by magicwang-cn** [comment]
ok, i see.

**Comment by ganisback** [comment]
I am also meet this unit test error when involve:
"github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/fake"

`
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:32:6: FakeIngressDNSRecords redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:32:6
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:37:5: ingressdnsrecordsResource redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:37:5
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:39:5: ingressdnsrecordsKind redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:39:5
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:42:33: (*FakeIngressDNSRecords).Get redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:42:6
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:53:33: (*FakeIngressDNSRecords).List redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:53:6
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:75:33: (*FakeIngressDNSRecords).Watch redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:75:6
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:82:33: (*FakeIngressDNSRecords).Create redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:82:6
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:32:6: FakeServiceDNSRecords redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:32:6
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:37:5: servicednsrecordsResource redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:37:5
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:39:5: servicednsrecordsKind redeclared in this block
	/Users/xzgan/go/src/github.com/xzgan/myproject/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:39:5
/Users/xzgan/go/src/github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:82:33: too many errors
`
