### ISSUE TITLE
Copy "config/federatedirectives" to federation v2 image

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#473]
Based on the comments here https://github.com/kubernetes-sigs/federation-v2/pull/432#issuecomment-440356504 , I was now trying to enable `kubefed2 federate enable` in a post-install job, but the problem is that I need to let the job know where are the files of `config/federatedirectives`, so here the proposal is put those files to the docker image of federation v2 and then we can call `/root/kubefed2 federate enable` in the docker container to generate all primitives.

/cc @marun

**Comment by marun** [comment]
I'm ok with adding the directives to the image.  

Once #400 and #480 are implemented, it will become possible to simplify configuration of `enable` to a list of types, so maybe the federate directive files can go away (at least for the purposes of initial deployment).

**Comment by gyliu513** [comment]
Based on discussion at https://kubernetes.slack.com/archives/C09R1PJR3/p1543936266022400?thread_ts=1543935228.020800&cid=C09R1PJR3 , I will try to use `kubefed2 federate enable` with `—dry-run —output=yaml` to generate some YAML templates, this will not require copying "config/federatedirectives" to federation v2 image, so closing this.
