### ISSUE TITLE
Created resources using manifest defined in examples failed.

### ISSUE THREAD

**Issue by qinpingli** [kubernetes-sigs/federation-v2#475]
kubectl apply -R -f https://github.com/kubernetes-sigs/federation-v2/blob/master/example/sample1/federatedconfigmap-placement.yaml
error: unable to recognize "example/federatedconfigmap-placement.yaml": no matches for core.federation.k8s.io/, Kind=FederatedConfigMapPlacement

apiversion should be: primitives.federation.k8s.io/v1alpha1

**Comment by marun** [comment]
Fixed by #476
