### ISSUE TITLE
Add kubectl to federation v2 image

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#483]
As I was planning to add a `pre-install` script for helm chart in https://github.com/kubernetes-sigs/federation-v2/issues/474 to disable federation via the following command:
```
# Disable federation of all types
for ftc in $(kubectl get federatedtypeconfig -n "${NS}" -o=jsonpath={.items..metadata.name}); do
  ./bin/kubefed2 federate disable "${ftc}" --delete-from-api --federation-namespace="${NS}"
done
```

And the above command need depend on `kubectl`, but the federation v2 image do not include this binary, we need to put `kubectl` to federation v2 image as well.

/cc @marun any comments for this?

**Comment by gyliu513** [comment]
`kubectl` is 53M.

```
root@gyliu-dev1:~/go/src/github.com/kubernetes-sigs/federation-v2/bin# du -sh kubectl
53M	kubectl
```

And the current federation v2 image is ~51M which build by myself.

```
root@gyliu-c12:~# docker images | grep fed
gyliu/federation-v2                                                   canary                         bb3cee9e92a0        4 hours ago         51.5MB
```

**Comment by marun** [comment]
I don't think `kubectl` should be added to the federation image. If we needed to consume it, we should rely on an official kube image.  I'm going to close this.

**Comment by gyliu513** [comment]
Based on discussion at https://kubernetes.slack.com/archives/C09R1PJR3/p1543936266022400?thread_ts=1543935228.020800&cid=C09R1PJR3 , I will try to use `kubefed2 federate enable’ with ‘—dry-run —output=yaml` to generate some YAML templates, this will not require kubectl, so closing this is good for me.
