### ISSUE TITLE
Added document for clusterSelector.

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/federation-v2#490]
With PR https://github.com/kubernetes-sigs/federation-v2/pull/484 , fed v2 now support placement policy with `clusterSelector`. But when joining a cluster to the federation controller plane, we cannot set labels for the joining cluster, it is better to enable `kubefed2 join` support adding labels.

My proposal here is adding a new option like `label` to `kubefed2` like `kubectl label`, and also enable `kubefed2 join` support `--label` option.

Setting label when joining a cluster:
```
./bin/kubefed2 join cluster1 --cluster-context cluster1 --host-cluster-context cluster1 --add-to-registry --v=2 --label foo=bar,foo1=bar1
```

Adding label to an existing federatedclusters:
```
kubefed2 label federatedclusters cluster1 foo=bar
```

Deleting label from an existing federatedclusters:
```
kubefed2 label federatedclusters cluster1 foo-
```

Currently, we can use `kubectl label federatedclusters` to set labels for federated clusters, so not sure if we still need `kubefed2 label`, but I think we need enable `kubefed2 join` support adding a federated cluster with some labels.

/cc @marun @kubernetes-sigs/federation-wg

**Comment by marun** [comment]
I don't think this should be the responsibility of `kubefed2`.  Labels are a part of every single kube resource, and there is a wealth of existing tooling and commands that allow them to be edited.  The best code is the code we don't have to write.

**Comment by gyliu513** [comment]
@marun so for now, if an end user want to add labels for the federated clusters, then two steps are needed: 

- Join the cluster
- Label the cluster via `kubectl label federatedclusters`

Shall we update the document a bit by clarifying this?

**Comment by marun** [comment]
Maybe add a pointer to the kube docs on labeling?

Also, just because label selection is supported doesn't mean that clusters need to be labeled.  I think the base use case is distributing resources to all clusters, and an empty selector will ensure that regardless of whether clusters are labeled or not.
