### ISSUE TITLE
[Docs Request] How-to update Federation Control Plane

### ISSUE THREAD

**Issue by mvazquezc** [kubernetes-sigs/federation-v2#500]
Hello,

I tried to update the Federation Control Plane from 0.0.2 to the latest available version (Canary) which includes the GenericOverride feature and it seems that updating the control plane is not as straightforward as changing the Operator's image.

I've been looking for documentation about how to update the control plane the right way, but I didn't find anything.

Could you provide some info about the update process? 

Thanks in advance!

**Comment by marun** [comment]
There is no update procedure defined at this time.  Redeploying federation is suggested.  Once we approach beta (early next year) we'll need to consider an upgrade path, but at this time fedv2 is alpha and the focus is on converging on a supportable solution.

**Comment by mvazquezc** [comment]
Thanks for the information.

I'll remove and re-deploy the federation bits.
