### ISSUE TITLE
Overrides types in userguide not working.

### ISSUE THREAD

**Issue by klingeleersbenjamin** [kubernetes-sigs/federation-v2#501]
I followed the federationv2 user guide. When i try to make test resources with

kubectl apply -R -f example/sample1

The overrides types are not working. The placement and templates types are working as expected.

unable to recognize "example/sample1/federatedconfigmap-override.yaml": no matches for kind "FederatedConfigMapOverride" in version "primitives.federation.k8s.io/v1alpha1"

unable to recognize "example/sample1/federateddeployment-override.yaml": no matches for kind "FederatedDeploymentOverride" in version "primitives.federation.k8s.io/v1alpha1"

unable to recognize "example/sample1/federatedjob-override.yaml": no matches for kind "FederatedJobOverride" in version "primitives.federation.k8s.io/v1alpha1"

unable to recognize "example/sample1/federatedsecret-override.yaml": no matches for kind "FederatedSecretOverride" in version "primitives.federation.k8s.io/v1alpha1"

**Comment by marun** [comment]
How did you install, and were there any error messages during the install?  Very strange to see just the override types missing.

**Comment by klingeleersbenjamin** [comment]
I installed the clusters following this guide

https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/environments/gke.md

Then i tried to deploy the federation control plane with the provided script

./scripts/deploy-federation-latest.sh cluster2

I got some errors during this script about kubefed2 and my GOPATH,, but the control plane was up and running so i manually joined the federation with kubefed.

When i described the clusters they both were ready so i the federations seems te be working fine. Only the override types are not working, both template and placement are just fine.

**Comment by gyliu513** [comment]
I think this was fixed in https://github.com/kubernetes-sigs/federation-v2/pull/502 , can you help test this and close if test passed? @klingeleersbenjamin 

FYI @marun

**Comment by klingeleersbenjamin** [comment]
I will test it tomorrow at work!

**Comment by klingeleersbenjamin** [comment]
I changed the override yaml files but im getting the same issue as before

unable to recognize "example/sample1/federatedconfigmap-override.yaml": no matches for kind "FederatedConfigMapOverride" in version "primitives.federation.k8s.io/v1alpha1"

unable to recognize "example/sample1/federateddeployment-override.yaml": no match
es for kind "FederatedDeploymentOverride" in version "primitives.federation.k8s.io/v1alpha1"

unable to recognize "example/sample1/federatedjob-override.yaml": no matches for kind "FederatedJobOverride" in version "primitives.federation.k8s.io/v1alpha1"

unable to recognize "example/sample1/federatedsecret-override.yaml": no matches for kind "FederatedSecretOverride" in version "primitives.federation.k8s.io/v1alpha1"

The api doesnt recongnize the kind so i think the problem is somewhere else.

**Comment by klingeleersbenjamin** [comment]
During the deploy federation script i got these errors

cmd/kubefed2/kubefed2.go:27:2: cannot find package "github.com/kubernetes-sigs/federation-v2/pkg/kubefed2" in any of:
	/usr/lib/go-1.6/src/github.com/kubernetes-sigs/federation-v2/pkg/kubefed2 (from $GOROOT)
	($GOPATH not set)
cmd/kubefed2/kubefed2.go:24:2: cannot find package "k8s.io/apiserver/pkg/util/logs" in any of:
	/usr/lib/go-1.6/src/k8s.io/apiserver/pkg/util/logs (from $GOROOT)
	($GOPATH not set)
cmd/kubefed2/kubefed2.go:25:2: cannot find package "k8s.io/client-go/plugin/pkg/client/auth" in any of:
	/usr/lib/go-1.6/src/k8s.io/client-go/plugin/pkg/client/auth (from $GOROOT)
	($GOPATH not set)
root@ubuntu:/home/user/Desktop/fedv2/federation-v2# go install kubefed
can't load package: package kubefed: cannot find package "kubefed" in any of:
	/usr/lib/go-1.6/src/kubefed (from $GOROOT)
	($GOPATH not set)
root@ubuntu:/home/user/Desktop/fedv2/federation-v2# go install kubefed2
can't load package: package kubefed2: cannot find package "kubefed2" in any of:
	/usr/lib/go-1.6/src/kubefed2 (from $GOROOT)
	($GOPATH not set)


Maybe this is the cause?

**Comment by gyliu513** [comment]
Generic overrides working fine after @klingeleersbenjamin using master build.
