### ISSUE TITLE
Automate consistent update of primitive crds for helm chart

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#505]
As per a [comment](https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/pre-commit.sh#L162) in the CI script, there needs to be a way for any contributor to consistently update the primitive CRDs packaged with the helm chart.  

`kubefed2` depends on openapi schema to determine the validation for the CRDs it generates, and openapi needs to be sourced from a `kube-apiserver`.  The openapi schema will vary with the version of `kube-apiserver`, and it's not reasonable to expect that every contributor will be using the same version.  Instead, it should be possible to create a script that launches the version of `kube-apiserver` that is downloaded as part of `kubebuilder` and runs `kubefed2` against that server.  Since the same `kube-apiserver` version will be used in CI, this approach should allow the ci check linked above to be re-enabled.

**Comment by gyliu513** [comment]
FYI @xunpan
