### ISSUE TITLE
federatedclusters is not reachable

### ISSUE THREAD

**Issue by kc004** [kubernetes-sigs/federation-v2#507]
Kubernetes version: **v1.11.3**
Cluster joining method: **helm**
**Kubernetes using Rancher**

root@:~/go/src/github.com/kubernetes-sigs/federation-v2# **./bin/kubefed2 join on-prem --cluster-context on-prem --host-cluster-context on-prem --add-to-registry --v=2**

I1210 06:42:35.370728   13102 join.go:141] Args and flags: name on-prem, host: on-prem, host-system-namespace: federation-system, registry-namespace: kube-multicluster-public, kubeconfig: , cluster-context: on-prem, secret-name: , limited-scope: false, dry-run: false
I1210 06:42:35.372152   13102 join.go:195] Performing preflight checks.
I1210 06:42:35.887897   13102 join.go:283] Registering cluster: on-prem with the cluster registry.
I1210 06:42:36.077257   13102 join.go:292] Registered cluster: on-prem with the cluster registry.
I1210 06:42:36.077283   13102 join.go:216] Creating federation-system namespace in joining cluster
I1210 06:42:36.275758   13102 join.go:224] Created federation-system namespace in joining cluster
I1210 06:42:36.275779   13102 join.go:227] Creating cluster credentials secret
I1210 06:42:36.275789   13102 join.go:418] Creating service account in joining cluster: on-prem
I1210 06:42:36.465577   13102 join.go:428] Created service account: on-prem-on-prem in joining cluster: on-prem
I1210 06:42:36.465607   13102 join.go:444] Creating cluster role and binding for service account: on-prem-on-prem in joining cluster: on-prem
I1210 06:42:36.894540   13102 join.go:453] Created cluster role and binding for service account: on-prem-on-prem in joining cluster: on-prem
I1210 06:42:36.894561   13102 join.go:457] Creating common cluster role and binding for service account: on-prem-on-prem in joining cluster: on-prem
I1210 06:42:37.277343   13102 join.go:466] Created common cluster role and binding for service account: on-prem-on-prem in joining cluster: on-prem
I1210 06:42:37.277363   13102 join.go:469] Creating secret in host cluster: on-prem
I1210 06:42:37.646818   13102 join.go:696] Using secret named: on-prem-on-prem-token-nls9h
I1210 06:42:37.835650   13102 join.go:728] Created secret in host cluster named: on-prem-xw2hf
I1210 06:42:37.835673   13102 join.go:478] Created secret in host cluster: on-prem
I1210 06:42:37.835683   13102 join.go:237] Cluster credentials secret created
I1210 06:42:37.835690   13102 join.go:239] Creating federated cluster resource
I1210 06:42:38.027830   13102 join.go:248] Created federated cluster resource

root@:~/go/src/github.com/kubernetes-sigs/federation-v2# **./bin/kubefed2 join aws-fed --cluster-context aws-fed --host-cluster-context on-prem --add-to-registry --v=2**
......same as above cluster.......

There were no error while joining the cluster.

**When i see federation-controller-manager logs:**
E1210 07:53:38.554801 1 reflector.go:205] github.com/kubernetes-sigs/federation-v2/pkg/controller/sync/controller.go:271: Failed to list <nil>: the server could not find the requested resource (get federatedjobs.core.federation.k8s.io)
E1210 07:53:38.555751 1 reflector.go:205] github.com/kubernetes-sigs/federation-v2/pkg/controller/sync/controller.go:271: Failed to list <nil>: the server could not find the requested resource (get federatedservices.core.federation.k8s.io)
E1210 07:53:38.691743 1 clusterclient.go:122] Failed to list nodes while getting zone names: Get https://kubernetes-api/k8s/clusters/xxxx/api/v1/nodes: x509: certificate signed by unknown authority
W1210 07:53:38.691776 1 controller.go:224] Failed to get zones and region for cluster with client {0xc420cd24b0}: Get https://kubernetes-api/k8s/clusters/xxxx/api/v1/nodes: x509: certificate signed by unknown authority

and when I describe federatedclusters It shows me clusters are unreachable. 

**kubectl -n federation-system describe federatedclusters**

Name:         aws-fed
Namespace:    federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.federation.k8s.io/v1alpha1
Kind:         FederatedCluster
Metadata:
  Creation Timestamp:  2018-12-10T06:43:13Z
  Generation:          1
  Resource Version:    595684
  Self Link:           /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/aws-fed
  UID:                 xxxxxx
Spec:
  Cluster Ref:
    Name:  aws-fed
  Secret Ref:
    Name:  aws-fed-p5tvx
Status:
  Conditions:
    Last Probe Time:       2018-12-10T07:20:14Z
    Last Transition Time:  2018-12-10T06:43:27Z
    Message:               cluster is not reachable
    Reason:                ClusterNotReachable
    Status:                True
    Type:                  Offline
Events:                    <none>

Name:         on-prem
Namespace:    federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.federation.k8s.io/v1alpha1
Kind:         FederatedCluster
Metadata:
  Creation Timestamp:  2018-12-10T06:42:37Z
  Generation:          1
  Resource Version:    595686
  Self Link:           /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/on-prem
  UID:                 xxxxxx
Spec:
  Cluster Ref:
    Name:  on-prem
  Secret Ref:
    Name:  on-prem-xw2hf
Status:
  Conditions:
    Last Probe Time:       2018-12-10T07:20:14Z
    Last Transition Time:  2018-12-10T06:42:46Z
    Message:               cluster is not reachable
    Reason:                ClusterNotReachable
    Status:                True
    Type:                  Offline
Events:                    <none>

**Comment by marun** [comment]
@kc004 I would also appreciate more detail of the method of installation.  I would also note that the 
`https://github.com/kubernetes-sigs/federation-v2/releases/tag/v0.0.4` release is now available and encourage you to attempt deployment with that, as there have been considerable changes since `v0.0.3` and previous releases will fedv2 remains in alpha are not supportable.

**Comment by marun** [comment]
It looks like initialization of the primitive crds isn't yet complete when the controller is started, but become initialized eventually such that the  `Failed to list` errors are temporary.  Are you still seeing the clusters not become ready?

**Comment by marun** [comment]
Given the lack of activity on this issue, I'm closing.  Feel free to reopen if necessary.
