### ISSUE TITLE
delete-federation.sh script doesn't take care of FederatedItems

### ISSUE THREAD

**Issue by mvazquezc** [kubernetes-sigs/federation-v2#510]
If this script is used without deleting the federated objects beforehand the ControlPlane won't be deleted.

I think this script should wether show a disclaimer or ask the user for confirmation in order to delete federated objects.

To my understanding, it should be enough if `FederatedClusterRole` and Namespaces associated with a `FederatedNamespacePlacemen`are deleted from the Host Cluster. 

What do you think?

**Comment by gyliu513** [comment]
@mvazquezc +1 to your proposal, can you please create a PR to update the document at https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#cleanup to claim this first?

Actually, we already cleaned up the resources at https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#example-cleanup , but it would be great if we can highlight this again before delete federation.

**Comment by gyliu513** [comment]
@mvazquezc can you close this issue as the PR was merged?

**Comment by mvazquezc** [comment]
Sure.
