### ISSUE TITLE
need help with fed2

### ISSUE THREAD

**Issue by andreypetruk** [kubernetes-sigs/federation-v2#523]
Hi all,

was created two cluster GKE - cluster11, cluster12)  then on cluster12  was deployed fed2 using helm. and joined cluster12 and cluster11.

---
ame:         cluster11
Namespace:    federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.federation.k8s.io/v1alpha1
Kind:         FederatedCluster
Metadata:
  Creation Timestamp:  2018-12-18T13:42:38Z
  Generation:          1
  Resource Version:    11937
  Self Link:           /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster11
  UID:                 c8681719-02ca-11e9-8b40-42010a960067
Spec:
  Cluster Ref:
    Name:  cluster11
  Secret Ref:
    Name:  cluster11-hfdc5
Status:
  Conditions:
    Last Probe Time:       2018-12-18T13:58:20Z
    Last Transition Time:  2018-12-18T13:42:58Z
    Message:               /healthz responded with ok
    Reason:                ClusterReady
    Status:                True
    Type:                  Ready
  Region:                  us-east4
  Zone:                    us-east4-a
Events:                    <none>

Name:         cluster12
Namespace:    federation-system
Labels:       <none>
Annotations:  <none>
API Version:  core.federation.k8s.io/v1alpha1
Kind:         FederatedCluster
Metadata:
  Creation Timestamp:  2018-12-18T13:40:59Z
  Generation:          1
  Resource Version:    11939
  Self Link:           /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster12
  UID:                 8decac03-02ca-11e9-8b40-42010a960067
Spec:
  Cluster Ref:
    Name:  cluster12
  Secret Ref:
    Name:  cluster12-m77rd
Status:
  Conditions:
    Last Probe Time:       2018-12-18T13:58:20Z
    Last Transition Time:  2018-12-18T13:41:37Z
    Message:               /healthz responded with ok
    Reason:                ClusterReady
    Status:                True
    Type:                  Ready
  Region:                  us-east4
  Zone:                    us-east4-b
Events:                    <none>
--- 

but on logs federation-controller-manager-0 I have
---
I1218 13:40:59.878755       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.879003       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.879072       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.879140       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.879216       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.883145       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.883275       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.883434       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.883627       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.883787       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.883929       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.884075       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.884171       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.884694       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.884785       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:40:59.884867       1 federated_informer.go:214] Cluster federation-system/cluster12 not added; it is not ready.
I1218 13:41:38.013683       1 controller.go:200] There is no status stored for cluster: cluster12 before
I1218 13:42:37.988196       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.988573       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989054       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989107       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989157       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989218       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989268       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989343       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989584       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989656       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989742       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989808       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989872       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.989925       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.990026       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:37.990081       1 federated_informer.go:214] Cluster federation-system/cluster11 not added; it is not ready.
I1218 13:42:58.213706       1 controller.go:200] There is no status stored for cluster: cluster11 before
---

Then I try deploy test ns. On cluster12(main) ns created, on cluster11 no.
--
I1218 13:42:58.213706       1 controller.go:200] There is no status stored for cluster: cluster11 before
E1218 13:55:45.527439       1 controller.go:507] Failed to execute updates for Namespace "test-namespace": [Failed to delete Namespace "test-namespace" in cluster cluster11: Operation cannot be fulfilled on namespaces "test-namespace": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.]
E1218 13:55:50.846478       1 controller.go:507] Failed to execute updates for Namespace "test-namespace": [Failed to delete Namespace "test-namespace" in cluster cluster11: Operation cannot be fulfilled on namespaces "test-namespace": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.]
-- 

then I edit federatedclusterrole-placement.yaml and change clusterNames to my cluster11 and cluster12. Now ns was created but on logs I got:

--
E1218 14:47:22.487826       1 manager.go:332] Failed to update status of ClusterPropagatedVersion "test-namespace/namespace-test-namespace": Operation cannot be fulfilled on clusterpropagatedversions.core.federation.k8s.io "namespace-test-namespace": StorageError: invalid object, Code: 4, Key: /registry/core.federation.k8s.io/clusterpropagatedversions/namespace-test-namespace, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 9dc30e5b-02cc-11e9-8b40-42010a960067, UID in object meta:

**Comment by marun** [comment]
@andreypetruk What version of Kubernetes are the GKE clusters?  And what release of federation -  v0.0.4?

**Comment by gyliu513** [comment]
@andreypetruk we actually have a document for how to run fed v2 on GKE at https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/environments/gke.md

FYI @danehans

**Comment by andreypetruk** [comment]
@marun 1.11.5-gke.5, federation from helm   
repository: quay.io/kubernetes-multicluster
  image: federation-v2
  tag: canary

**Comment by andreypetruk** [comment]
@gyliu513 yep I know, my steps was mostly the same. I only use the latest version K8S from GKE

**Comment by marun** [comment]
I don't think the last error you reported (`Failed to update status...`) is a problem, it just indicate that a status write will be retried.  I've proposed to downgrad it to a warning in #529.

**Comment by marun** [comment]
@andreypetruk Closing since I haven't heard a response in more than 60 days.  Feel free to re-open if needed.
