### ISSUE TITLE
need healthcheck with federation-controller-manager

### ISSUE THREAD

**Issue by tianzhuozhuo** [kubernetes-sigs/federation-v2#535]

**Comment by marun** [comment]
@tianzhuozhuo A health-check is certainly suggested as fedv2 becomes something that needs to be supported, but we're still in alpha now and there is lots of other work still to do.  Would you be willing to document your reasons for filing this issue so there are rationale justifying prioritization?

**Comment by poothia** [comment]
I would like to explore this and work on this.

**Comment by shashidharatd** [comment]
This is addressed with https://github.com/kubernetes-sigs/federation-v2/pull/824
