### ISSUE TITLE
federation finalizer is tagged to kubernetes namespace 

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/federation-v2#538]
After federation is deleted from cluster, the host cluster namespace still tagged by federation finalizer.
```
$ kubectl get ns default -o yaml
...
  finalizers:
  - federation.kubernetes.io/delete-from-underlying-clusters
  - orphan
...
$ kubectl get ns kube-public -o yaml
...
  finalizers:
  - federation.kubernetes.io/delete-from-underlying-clusters
  - orphan
...

```

**Comment by marun** [comment]
I appreciate your filing this issue. The strategy of always applying finalizers to resources is a legacy of fedv1, and potentially harmful for fedv2.  It may be preferable to avoid applying a finalizer to a resource unless resources are expected to exist in member clusters (i.e. remove a finalizer if no clusters are selected and resources have been confirmed to have been removed from all member clusters).
