### ISSUE TITLE
resource in joined cluster will be deleted if federatedresource is created with the same name

### ISSUE THREAD

**Issue by braceinhz** [kubernetes-sigs/federation-v2#549]
**What would you like to be added**: I create a deployment named nginx in joined cluster,then create a nginx federateddeployment in the kubernetes federation, the old nginx deployment will be deleted ,with nginx federateddeployment create new one.

**Why is this needed**:This will causing business disruption

/kind feature

**Comment by xunpan** [comment]
This seems a case that a resource created in member cluster has same name within same namespace for a federation propagated resource. It shows 2 ways to create a resource which have conflict.

To make federation only manages its own resource, federation needs to identify all federation propagated resources in each member cluster. Only propagated resources need to be deleted when the federated resource placement is changed. But, this also makes it complex considering:
    1. nginx is created by local user and used for his purpose.
    2. federation also propagate a nginx resource to the cluster.
In such case, it is not easy to define federation behavior on this member cluster:
    1. delete old one and create new one for federation. It is bad as logged.
    2. keep old nginx exists. It is also not good because federation placement is not met.

So, I think the better way is to make federation control plane manages several namespaces it can be operated on and make each cluster member does not use such namespace with RBAC in local cluster to avoid function conflict.

**Comment by marun** [comment]
@xunpan I don't think it is desirable for fedv2 to 'only manage its own resources', at least not explicitly.   A user or administrator can always implement a permission scheme to achieve custom behavior as you're describing, but I don't think the community should be responsible for supporting those schemes.  Otherwise the complexity of federation will be unbounded.

**Comment by irfanurrehman** [comment]
After the label selector based placement in place there are now two aspects of this issue

1. The resource placement 
    The resource is placed in all clusters including new clusters joining. If resource exists in new cluster joining it will be adopted by federation. To achieve this there is now an option of using an empty label selector to result in placement into all clusters at any time. One can use empty selector as described [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#specplacementclusternames-is-not-provided-specplacementclusterselector-is-provided-but-empty).  One can also use specific labels on the cluster object while creating the cluster object (or joining the cluster; this option is not there with join as of now but can be added) to have different placement policy then `all clusters` and still have resource not deleted from new joining cluster.
2. The pre exiting object in the new joining cluster will be overwritten by the clusterobject created/selected by federation using the federated object and overrides if any. Its debatable if this should be treated as an issue. However ownerRef or some reserved label on the federation created resources might make sense for controllers to be able to differentiate between the two and fix a default behaviour (preferably on the the safer side that the local resource is not delete/overwritten by federation). User can provide a switch in spec to select the behavour. Also the resource status can reflect `what happened` for a given cluster.

@marun @xunpan I think the latter part in 2 seems like a valid feature to implement. What do you say?
cc @shashidharatd @pmorie @magicwang-cn

**Comment by magicwang-cn** [comment]
i agree with @irfanurrehman . 'ownerReference' is needed for k8s resource which related with federated resource. we should remind users that the same name resource has been existed in the cluster instead of deleting it directly.

**Comment by marun** [comment]
As per discussion in yesterday's wg meeting with @shashidharatd , I think it makes sense to allow the federation's behavior regarding existing resources to be configurable.  In addition to the requirement expressed thus far on this issue - that it would be desirable for federation to avoid managing existing resources - other use cases require that federation manage resources in member clusters regardless of whether they were created by federation.  I think that precludes supporting only a single behavior.

Regarding the suggestion that `ownerReference` be used as a way of indicating ownership, that is not possible.  `ownerReference` is a cluster-local concept, and a federated resource exists in a difference cluster than any of the resources it manages in member clusters.  An `ownerReference` referring to a resource that does not exist in the same cluster will ensure the removal of the owned resource by the garbage collector.

I am working to ensuring that managed resources are labeled (e.g. `federation.k8s.io/managed: true`) to limit the scope of the federated informers to managed resources as part of #612.  Subsequent work could ensure that unlabeled resources could be configurably ignored by the sync controller.
