### ISSUE TITLE
Generated CRDs prone to name collisions

### ISSUE THREAD

**Issue by fabxc** [kubernetes-sigs/federation-v2#550]
When enabling a resource of <kind> for federation, several CRDs are created:

* `federated<kind>.primitives.federation.k8s.io`
* `federated<kind>overrides.primitives.federation.k8s.io`
* `federated<kind>placements.primitives.federation.k8s.io`

This disregards the API group that namespaces the kind. Thus it's not possible to federate two distinct resources with the same kind name. 

While this seems overall like an unlikely edge case, it could certainly happen and seems to be a pretty fundamental blocker in those cases.
The obvious solution might be to move to `federated<kind>overrides.<api_group>.primitives.federation.k8s.io`. OTOH, the kind of the federated resources would become something like `FedereatedDeploymentMyCustomGroupComOverrides`, which seems pretty unusable too.

/kind bug

**Comment by marun** [comment]
The negative consequence of kind name clashes is having to specify the api group with every invocation of `kubectl`.   I think this is sufficient disincentive for duplicate kind names even in different api groups.  For those cases where someone has ignored this problem (to the obvious detriment of their users), `kubefed2 federate` supports specifying `--primitive-group`.  I think that is a preferable solution to forcing all primitives to be qualified with api group.

FYI, I will be shortly be posting a proposal to unify the primitives into a single type (e.g. FederatedFoo will contain `template`, `overrides` and `placement` fields), which should simplify things.

**Comment by marun** [comment]
I think the ability to override the group of the generated CRD renders this bug invalid.  Feel free to reopen if you disagree.
