### ISSUE TITLE
Install multiple namespaced fedeartion is failed

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/federation-v2#557]
**What happened**:
1. When second namespaced federation is deployed by deployment script. The operation is failed.

```
$ FEDERATION_NAMESPACE=foo NAMESPACED=y ./scripts/deploy-federation.sh happur/fedv2:test cluster2
...
$ # done successfully

$ FEDERATION_NAMESPACE=dup NAMESPACED=y ./scripts/deploy-federation.sh happur/fedv2:test cluster2
...
F0122 22:15:08.855409    2580 enable.go:117] error: Error creating CRD "federatedclusterroles.primitives.federation.k8s.io": customresourcedefinitions.apiextensions.k8s.io "federatedclusterroles.primitives.federation.k8s.io" already exists
```

2. When skip federate step in the script and manually join cluster. It still failed in
```
I0123 01:25:33.795001    5923 join.go:630] Could not create health check cluster role for service account: cluster2-cluster1 in joining cluster: cluster2 due to: clusterroles.rbac.authorization.k8s.io "federation-controller-manager:healthcheck-cluster2-cluster1" already exists
```
The reason is that our health check uses cluster role.

**What you expected to happen**:
Namespaced federation shold deployed for multiple instances.

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version
- Install method (helm vs script)
both of them have this issue

- Install configuration (namespaced vs cluster-scoped)
namespaced

- Others

/kind bug

**Comment by gyliu513** [comment]
@xunpan for second error, I think we do not support adding one cluster to multiple federation controllers, each cluster can only join one federation controller.

The first one is indeed an issue, not only for install but also for delete, as delete will delete all of the CRDs as well, and this will cause other federation controllers does not work.

**Comment by xunpan** [comment]
As we support namespaced federation, I think we should support one cluster in multiple namespaced federation. @marun 

@font what is the reason to create service account (which bind to healthcheck role), e.g. cluster1-cluster1. 
```
        saName, err := createServiceAccount(joiningClusterClientset, namespace, joiningClusterName, hostClusterName, dryRun)     
```
It is created by `join` and deleted by `unjoin`. I did not see any controller or place to use it. Is there something I lost?

**Comment by gyliu513** [comment]
FYI @marun @shashidharatd @irfanurrehman @pmorie

**Comment by gyliu513** [comment]
An option is we can move the CRDs out and make a separate chart for CRDs, then use a flag `crds.enabled` to control install CRD or not, let me get some comments from helm chart community first at https://github.com/helm/helm/issues/5201

@xunpan I think the deploy in multiple namespaces should succeed when install federation with scripts, but if you delete one federation controller from the cluster, other federations will not work as the CRDs are deleted. Perhaps the delete logic in scripts need some update?

**Comment by xunpan** [comment]
> @font what is the reason to create service account (which bind to healthcheck role), e.g. cluster1-cluster1.
> 
> ```
>         saName, err := createServiceAccount(joiningClusterClientset, namespace, joiningClusterName, hostClusterName, dryRun)     
> ```
> 
> It is created by `join` and deleted by `unjoin`. I did not see any controller or place to use it. Is there something I lost?

 I guess I understand the reason.
This SA creates a secret on member cluster. Joining operation creates a secret on host cluster with the data of member cluster secret.
This secret will be used for federatedcluster controller to detect member cluster status.

**Comment by marun** [comment]
The health check is necessarily a cluster-scoped role.  The name of the cluster-scoped role for a namespaced deployment should reflect the namespace that federation is deployed to so that multiple deployments do not clash (or share a common cluster role).

**Comment by gyliu513** [comment]
@xunpan @marun the CRD can be checked as follows after some discussion with helm community:

```yaml
{{- if (and .Values.crds.enabled (not (.Capabilities.APIVersions.Has "clusterregistry.k8s.io/v1alpha1"))) }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  labels:
    api: ""
    kubebuilder.k8s.io: 0.1.10
  name: clusters.clusterregistry.k8s.io
spec:
  group: clusterregistry.k8s.io
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
{{- end }}
```

**Comment by marun** [comment]
@gyliu513 Thank you for investigating.  I'm assuming helm's current ability to detect cluster capabilities predates CRDs being a thing, because an apiversion being present is a very weak guarantee that a crd will be present.  Does helm have the equivalent of `kubectl apply` so that application of yaml would be idempotent?

**Comment by gyliu513** [comment]
@marun I think helm do not want to have `kubectl apply` feature, as for this case, the install will be succeed if we install multiple times, but for delete, one delete will delete all resources, and other helm releases will not have the deleted resources any more, this may cause the other helm releases will not work.

So for now, how about use the solution to add a `enabled` parameter to do the checking to decide if we want to install CRD or not?

**Comment by marun** [comment]
@gyliu513 Yes, the enabled parameter is fine for now.   In the future, I would expect to want to transition to a tool with better support for what we're trying to do (maybe an operator?) if helm continues to lag behind the kube state-of-the-art.
