### ISSUE TITLE
Idea: multicluster service DNS

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#56]
We should have an easy way to implement DNS provider integration for multi-cluster service DNS.

Goals:

- Make a vendor-independent DNS controller that does 99% of the work for you of monitoring service resources in multiple clusters and writing an intermediate resource which is the interface for vendor implementations to program to
- Vendors implement controllers that program their DNS solutions by reconciling the intermediate resource

### TLDR

_Note: names have been chosen carelessly to avoid wasting time, we can figure out best names later_

TLDR: The work common to every implementation of multicluster DNS can be done by a controller that watches Kubernetes `Service` resources in multiple clusters and maintains a resource (for sake of discussion, let's call it `MultiClusterServiceDNS`) where each instance of the resource is DNS information for a single service. Vendors implement controllers that watch `MultiClusterServiceDNS` and program their DNS solution.

### Dependencies

- Cluster Registry to hold a list of clusters you care about
- FederatedCluster resource to specify how to talk to each cluster you're interested in

### Resources

The `MultiClusterServiceDNS` programs the dns controller to monitor a set of services. Here's a very simple example with toy semantics to illustrate the idea.

Resources of this type are aligned with K8s services via name/namespace association:

- `metadata.namespace` is the namespace to monitor in each specified cluster
- `metadata.name` is the name of the service in the namespace to monitor in each specified cluster

The spec contains information about the clusters to monitor and how to program DNS:

- `spec.dnsName` is the DNS name to program
- `spec.clusters` is a list of clusters to monitor

These are just toy semantics for illustration purposes; actual semantics TBD.

```yaml
kind: MultiClusterServiceDNS
apiVersion: dns.multicluster.k8s.io
metadata:
  name: my-service
  namespace: my-ns
spec:
  dnsName: my-service.myorg.org
  clusters:
  - X
  - Y
  - Z
status:
  dns:
  - cluster: us-central-1
    ip: 123.4.5.0
  - cluster: us-east-1
    ip: 4.5.6.7
  - cluster: us-west-1
    ip: 10.1.254.5
```

Vendors integrate with this API by writing controllers that list/watch `MultiClusterServiceDNS` and program their DNS solutions.

Note: in the above example, a controller maintains the list of (cluster name, IP) pairs in the status of the `MultiClusterServiceDNS` resource. It is likely that `status` is not the best place for this information. When we discussed this idea in the April 18 2018 meeting of the Federation WG, we discussed a number of possibilities:

- Have a controller put the endpoint information into another resource's spec; the `MultiClusterServiceDNS` resource's status would contain information on what resourceVersion the controller had seen and whether their was a problem communicating with one of the named clusters
- Additionally, a new resource named in the previous bullet could be a new source in [external-dns](https://github.com/kubernetes-incubator/external-dns)
- Alternatively, we could instead add a new generic DNS resource to external-dns and have a controller that populated that new resource

Additionally, we discussed emulating the behavior of the [v1 federation dns solution](https://kubernetes.io/docs/tasks/federation/federation-service-discovery) and programming additional DNS names with cluster/zone information, examples:

- `my-service.my-ns.myfederation.svc.myorg.org`
- `my-service.my-ns.myfederation.svc.us-central-1.myorg.org`
- `my-service.my-ns.myfederation.svc.us-east-1.myorg.org`
- `my-service.my-ns.myfederation.svc.us-west-1.myorg.org`

**Comment by pmorie** [comment]
cc @shashidharatd

**Comment by shashidharatd** [comment]
This issue has been addressed and the implementation is available.
