### ISSUE TITLE
User guide shoud state implicit GOPATH dependency

### ISSUE THREAD

**Issue by llarsson** [kubernetes-sigs/federation-v2#565]
**What happened**:

Trying to run through the User Guide from some other directory than `${GOPATH}/src/github.com/kubernetes-sigs/federation-v2` fails while downloading binaries and cannot build federation using scripts.

Making sure to clone to the `${GOPATH}/src/github.com/kubernetes-sigs/federation-v2` directory works as intended.

**What you expected to happen**:

Since nothing was stated about which directory is OK to clone the repo to, I expected the User Guide to work.

**How to reproduce it (as minimally and precisely as possible)**:

 1. Check out the repo to a path under e.g. `/tmp`.
 2. Deploy some clusters.
 3. Try to run `./scripts/download-binaries.sh` and watch `kubebuilder` complain about not running in the right place.
 4. Try to run `./scripts/deploy-federation-latest.sh cluster2` and watch it fail while building Go code.

/kind bug

**Comment by matti** [comment]
well, I also stumbled in to this - I wouldn't clone the repo, but helm install failed with

```
"federatedclusters.core.federation.k8s.io" already exists
```

**Comment by marun** [comment]
@matti That error message indicates that installation had already been attemped on the target cluster.  Attempting re-installation will fail because the crds have already been installed.

**Comment by matti** [comment]
@marun yeah I figured that out later when I actually understood what was happening.

**Comment by aviweit** [comment]
I also suggest to denote GOPATH setting in userguide, as @llarsson mentions (even just as an aside comment). I encountered same issue yesterday when attempting to install federation v2.

Thanks.

**Comment by marun** [comment]
I don't think the userguide should require mention GOPATH, so I'll take it as an action item to limit it to documenting deployment with helm.  Script-based deployment is likely to go away, and while it remains it is very much intended for developers only.

**Comment by llarsson** [comment]
Good! As long as a user does not fail with their experiments because they need implicit knowledge of what language the software was written in and therefore know what steps to take to set up a development environment, I am satisfied. 😀 Because as a user, I do not typically expect that.

On March 14, 2019 6:30:08 PM GMT+01:00, Maru Newby <notifications@github.com> wrote:
>I don't think the userguide should require mention GOPATH, so I'll take
>it as an action item to limit it to documenting deployment with helm. 
>Script-based deployment is likely to go away, and while it remains it
>is very much intended for developers only.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kubernetes-sigs/federation-v2/issues/565#issuecomment-472977746

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
