### ISSUE TITLE
A way to prevent controller from overwriting certain fields

### ISSUE THREAD

**Issue by lyxsus** [kubernetes-sigs/federation-v2#570]
**What would you like to be added**:
I would like to have a way to define a list of fields for resource that if they're updated on some cluster won't trigger federation controller to sync and overwrite them.

**Why is this needed**:
I want to specify, which clusters contain my deployment and I want local versions of HPA to scale them based on local usage.

I have federated Deployment an federated HPA (enabled) defined
https://gist.github.com/lyxsus/bca5bb7ab95ebd014b60186fa3882357

I expected deployment to be scaled up to 2, instead federation controller and HPA started to race for "replicas" field, oscillating number of pods between 1 and ~2:
https://gist.github.com/lyxsus/7d705ef4ba726897277b6429f13fc822

Initially, I thought there must be some property in FederatedDeployment like `minReplicas` and `maxReplicas` for this use case, but that isn't the case and talks on Slack suggested that it's more general problem and a case where Service NodePorts and ExternalIP fields were undesirably overwritten in a same way.

/kind feature

**Comment by marun** [comment]
@lyxsus I'm going to implement a workaround for HPA in advance of a more general-purpose solution.
