### ISSUE TITLE
Skip Travis build for doc-only changes

### ISSUE THREAD

**Issue by poothia** [kubernetes-sigs/federation-v2#575]
The Travis CI build is triggered regardless of changes made in the PR, Which is not a desirable outcome in case of doc-only changes.

There is an open Issue in travis CI (https://github.com/travis-ci/travis-ci/issues/6301) for the same, but as it's not being followed up, other repos have implemented it on their side.

Ref:
https://github.com/facebook/react/issues/1768
https://github.com/serverless/serverless/issues/2699

**Comment by poothia** [comment]
if this is a desireable change, i would like to work on it.

**Comment by marun** [comment]
@poothia What is required to implement this feature?

**Comment by poothia** [comment]
@marun i think adding a check in `travis.yml` to check if only changed files are `.md` files then it should exit without making the whole build should be enough. if you say so, i can update a WIP PR to see the same.

**Comment by marun** [comment]
@poothia If that's the case, then please go ahead.  It wasn't clear to me from the provided links that direct travis support was available.
