### ISSUE TITLE
kubefed2 join does not work correctly with some kubectl context names for the hosting cluster

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#577]
**What happened**:

I used `kubefed2 join` with a cluster whose kubectl context contained a slash (`default/pmorie-dev-api-devcluster-openshift-com:6443/kube:admin`), which is a perfectly valid kubectl context name. However, the name of the kubectl context for the host cluster is used to construct the names of resources, which will yield invalid resource names in cases like this where the name of the kubectl context is a valid context name but not a valid resource name. We should construct the names of these resources using values that will always yield a valid resource name.

Looking at possibilities for which value to use, I thought about using the name of the cluster in the kubeconfig (instead of the name of the context), but it appears there are basically no validation requirements for kubeconfig cluster names: https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/validation.go#L167

Tactically, perhaps we could consider using `-federation` when we construct resource names.

**What you expected to happen**:

I would expect the join operator to proceed even if my context name does not construct a valid k8s resource name.

**How to reproduce it (as minimally and precisely as possible)**:

Use `kubefed2 join` with a host cluster context that contains a slash.

/kind bug

**Comment by shashidharatd** [comment]
@pmorie, can this be closed?

**Comment by marun** [comment]
Fixed by #578
