### ISSUE TITLE
a cluster should know if it has been joined or not

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/federation-v2#585]
**What would you like to be added**:
A way to know if cluster is joined or not.

I could not find any way to determine this - a namespace "kube-multicluster-public" is created in the cluster, but it is not deleted when the cluster has been unjoined.

**Why is this needed**:

To support scenarios where something needs to be done in cluster unjoin - for example clean up deployments as described in #583
 

/kind feature

**Comment by marun** [comment]
As per commentary in #583, the federated control plane is the source of truth as to whether a cluster is joined or not, and cleanup of federated resources is the responsibility of the federated control plane.  I don't think this issue has sufficient details that would justify a mechanism for determining whether a cluster was a member of a federation separate from the federation control plane.

**Comment by matti** [comment]
In my topology the member cluster has no access to the federated control plane - the control plane is not deployed in the member cluster.

So therefore I want to build a cleanup mechanism that starts when the cluster has been unjoined.

I don't think this is unreasonable request as the member cluster already knows that it has been joined OR it has been member (because the namespace is not deleted)

**Comment by marun** [comment]
My point is that the place for cleanup to be initiated from is the federation control plane, which would be expected to have access to the member cluster.  Any other solution would require that federation annotate every resource that it propogates to (or adopts in a) member cluster, and I don't think the bar for making that kind of sweeping change has been reached yet.

Cleanup initiated via the federation control plane could be the result of removing placement from all federated resources for a cluster intended for removal from the federation.  That would work for explicit (`clusterName`) based placement.  To ensure cleanup where `clusterSelector` was used, it might be necessary to add a new field to `FederatedCluster` indicating that it should not be selected (e.g. `selectable: false`).  I can see value in unjoin growing the ability to optionally perform this kind of cleanup before removing a member from the federation.

**Comment by matti** [comment]
I'm already annotating my resources, it's not a big thing to do.

This is how I deploy currently:
```
apiVersion: scheduling.federation.k8s.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: deployment
  namespace: default
spec:
  targetKind: FederatedDeployment
  rebalance: true
  totalReplicas: 100000
  clusters:
    "*":
      weight: 1
    main:
      maxReplicas: 0
      weight: 1
```

So every cluster ever joined gets replicas, but my "main" cluster does not (this is where I run federation control plane)

I have to delete resources after I issue the unjoin command and this gets interrupted, then resources are left running.

*but* if the cluster which has been unjoined is responsible for the cleanup, then it is guaranteed that resources are cleaned up eventually after this atomic "unjoin" operation.

**Comment by marun** [comment]
I encourage you to use the removal (or a change to the 'Terminating' phase) of the federation namespace (`federation-system` by default) in a member cluster as your signal that cleanup should commence.  I don't see there being a need to signal unjoin more than that, as from what I'm reading  your use case (and proposed solution) is very specific and not something that would apply generally to all federation resources.

**Comment by matti** [comment]
Hmm, okay - that might work - thanks for the tip.

**Comment by marun** [comment]
@matti Have you been able to use the termination of the federation namespace as an indication of unjoin?  And if so, does that satisfy your use case such that you would consider this bug resolved?

**Comment by matti** [comment]
yes, it works.
