### ISSUE TITLE
Helm sync script doesn't build kubefed2

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#589]
**What happened**:

Running `./scripts/sync-up-helm-chart.sh` did not update the helm chart after changes that affected the generation of federated type crds.

**What you expected to happen**:

`./scripts/sync-up-helm-chart.sh` to synchronize the state of the chart with the state of the code by building `kubefed2` before attempting to generate federated type yaml.

**How to reproduce it (as minimally and precisely as possible)**:

 - build kubefed2
 - make changes to kubefed2 code that affect crd generation
 - run `./scripts/sync-up-helm-chart.sh`

/kind bug

cc: @gyliu513

**Comment by gyliu513** [comment]
@marun `./scripts/sync-up-helm-chart.sh` was not rebuilding `kubefed2` as this script was only called by `./scripts/pre-commit.sh`, and `./scripts/pre-commit.sh` do have the logic to rebuild `kubefed2`. So if you run `./scripts/pre-commit.sh`, you should get the latest helm chart. But here I'm +1 with you, we should update `./scripts/sync-up-helm-chart.sh` to build the latest `kubefed2` as well to make sure we can sync up the helm chart with `./scripts/sync-up-helm-chart.sh`.

/assign @xunpan

**Comment by marun** [comment]
@gyliu513 I think we're in agreement that the script should ensure kubefed is built to simplify the life of developers updating the chart outside of the ci script.  A local go build is super cheap - it can detect that nothing has changed - but maybe the docker build performed by the makefile suggests the sync script accept a `BUILD_KUBEFED` flag that defaults to `y` and can be passed as empty when called from the ci script?
