### ISSUE TITLE
kubefed2 unjoin --force

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/federation-v2#592]
**What would you like to be added**:
`kubefed2 unjoin --force clusterthatnolongerexists`

**Why is this needed**:
Currently a cluster that does not exist cluster config can not be unjoined.

/kind feature

**Comment by cwilkers** [comment]
What is your kubefed2 version? Unjoin has a --force option in 0.0.4 (possibly 0.0.3 as well, I haven't looked when it was added...)

**Comment by matti** [comment]
Strange, I just checked using master and force was missing

**Comment by cwilkers** [comment]
I recently ran into the same problem, I'd updated the federation-v2 repo, but had an old (alpha 0.0.1) version of kubefed2 in my ~/bin

Try `kubefed2 version` to check.

**Comment by matti** [comment]
Hmm, actually my scripts compile it every time - I don't have it in any "bin"

https://github.com/kubernetes-sigs/federation-v2/issues/582

have to recheck

**Comment by marun** [comment]
@matti `--force` is indeed an option to unjoin and has been for some time.  Please close this issue once you've verified this for yourself.

**Comment by gyliu513** [comment]
@matti please refer to https://github.com/kubernetes-sigs/federation-v2/issues/188 and https://github.com/kubernetes-sigs/federation-v2/pull/431 for detail.

**Comment by xunpan** [comment]
`--force` cannot handle if a member cluster context does not exists or the member cluster cannot be accessed.

This is not good to me because we cannot sure if there has any admin operations break a member cluster assumptions in these ways.

@marun @gyliu513

**Comment by marun** [comment]
@xunpan I think you're correct that `unjoin --force` should be able to remove all trace of a member cluster from the host cluster even in the absence of the member cluster context.  The code at present will fail as soon as the cluster config can't be retrieved, which is not ideal.  `--force` should likely ignore that error.
