### ISSUE TITLE
Kubefed2 unjoin of cluster hosting control plane deletes federation control plane

### ISSUE THREAD

**Issue by cwilkers** [kubernetes-sigs/federation-v2#593]
**What happened**:
I was attempting to restore a previously installed control plane on a new cluster (minishift) for disaster recovery testing. Certificates did not match, so I attempted to unjoin/rejoin the host cluster to reestablish control, but the unjoin removed the federation-system namespace, thus deleting the federation-controller-manager-0 deployment config and all cluster definitions.

**What you expected to happen**:
Kubefed2 unjoin should not delete federation controller's namespace from the host cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Federate a cluster, then unjoin it. Observe that federation namespace is deleted, removing entire control plane as well as the connection.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)

Minishift with current OCP:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-02-08T23:07:29Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Federation version

git d474b39dd49

- Install method (helm vs script)

hack/latest

- Install configuration (namespaced vs cluster-scoped)

namespaced

- Others
kubefed2 version: version.Info{Version:"v0.0.4", GitCommit:"2cdf5d37240d9b8b33e2715deb75fbb7f9e003ad", GitTreeState:"clean", BuildDate:"2018-12-10T23:03:18Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

/kind bug

**Comment by matti** [comment]
if the namespace is removed, I can not rely on it here: https://github.com/kubernetes-sigs/federation-v2/issues/585#issuecomment-462391765

**Comment by cwilkers** [comment]
This may be a case for establishing a best practice of not adding the host cluster to its own federation.

**Comment by marun** [comment]
@cwilkers It's perfectly valid to add a host cluster to its own federation.  `unjoin` should be detecting that the federation namespace is in the host cluster and skipping deletion.

**Comment by marun** [comment]
@cwilkers Given that context names are necessarily unique in a kube config, what were the values for the host and unjoining cluster contexts for the unjoin invocation that removed the federation namespace from the host cluster?

**Comment by cwilkers** [comment]
@marun I did not specify the context for either cluster, they are both renamed to match the cluster name, in this case cluster1. Does the comparison code have access to the default context name of "cluster name" if left unspecified?

**Comment by marun** [comment]
@cwilkers It appears that the host cluster context is defaulted to `""` and this value is never converted to an explicit name (the config library will presumably determine the active context in the kubeconfig file).  I'm undecided as to whether it makes more sense to lookup the context name or compare the identity of federated namespaces to decide whether removal is warranted.

**Comment by cwilkers** [comment]
Unless there is another use for knowing the host cluster context during unjoin, I vote for comparing namespace identities -- I would expect fewer side effects.

**Comment by gyliu513** [comment]
@marun @cwilkers I was bit confused, do we need to support the command like this `kubefed2 unjoin --force clusterthatnolongerexists`? I think we need at least specify host cluster `host-cluster-context`, am I missing anything?

FYI @xunpan

**Comment by cwilkers** [comment]
@gyliu513 The documentation says the host-cluster-context is optional and the default is current-context:

```
$ kubefed2 help unjoin

		Unjoin removes a cluster from a federation.
		Current context is assumed to be a Kubernetes cluster
		hosting the federation control plane. Please use the
		--host-cluster-context flag otherwise.
```

The current thread does not deal with --force. You might be thinking about #592

**Comment by gyliu513** [comment]
> @gyliu513 The documentation says the host-cluster-context is optional and the default is current-context:

@cwilkers Yes, I think this is a small bug, as if `host-cluster-context` was not specified, then the service account will not be found and the cluster unjoin will be failed. I think we may need to update the CLI to make `HostClusterContext` as must have option. @marun comments?

```shell
$ kubefed2 unjoin cluster2 --force                                                                                                                                    
E0213 22:03:10.401859    6164 unjoin.go:278] Error deleting service account: cluster2- in unjoining cluster. serviceaccounts "cluster2-" not found
```

**Comment by marun** [comment]
@gyliu513 `--host-cluster-context` is only required if the currently active context is not the host context.

**Comment by gyliu513** [comment]
@marun thanks, yes, I see, then I think the current help info is good enough for end user.

```
            $ kubefed2 help unjoin

		Unjoin removes a cluster from a federation.
		Current context is assumed to be a Kubernetes cluster
		hosting the federation control plane. Please use the
		--host-cluster-context flag otherwise.
```
