### ISSUE TITLE
Objects stuck with finalizer "delete-from-underlying-clusters" 

### ISSUE THREAD

**Issue by mvazquezc** [kubernetes-sigs/federation-v2#603]
**What happened**:

Federated environment with 5 clusters, 2 of them are down.

We tried to remove a namespace that was federated across the 5 clusters, objects got stuck by finalizer `federation.kubernetes.io/delete-from-underlying-clusters`.

We couldn't remove non-available clusters using kubefed2 tool (before deleting the namespace).

When removing the finalizer manually, then the objects got stuck by finalizer `kubernetes` because the CRD instances in the project weren't deleted.

**What you expected to happen**:

Having some sort of configuration on the control plane where you can define a grace period for non-available clusters, after this grace period, those clusters wouldn't be taken into account for the finalizer `federation.kubernetes.io/delete-from-underlying-clusters`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Federate 2 clusters.
2. Deploy a federated workload.
3. Powerdown one of the clusters.
4. Try to delete the federated namespace from the host cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
```
openshift v3.11.43
kubernetes v1.11.0+d4cacc0
```
- Federation version
```
v0.0.4
```
- Install method (helm vs script)
```
script
```
- Install configuration (namespaced vs cluster-scoped)
```
cluster-scoped
```
- Others

/kind bug

**Comment by marun** [comment]
I don't think the solution is a configurable grace period.  As per a [comment](https://github.com/kubernetes-sigs/federation-v2/issues/591#issuecomment-463001664) in a related issue, there needs to be better documentation of the different ways to remove federated resources.

**Comment by mvazquezc** [comment]
Hi @marun,

Thanks for your help.

Using v0.0.5 and following the proper steps to delete a federatedNamespace it worked.

So basically we have two scenarios:

1. One of our clusters is down, but we can recover it
2. One of our clusters is down and we can't recover it

For the 1st scenario, the followed steps were:

1. `test-namespace` distributed across `cluster1` and `cluster2`
2. `cluster2` goes offline
3. We run `oc delete namespace test-namespace`
  3.1 Namespace has `kubernetes` finalizer
  3.2 Objects inside the namespace have `delete-from-underlying-clusters` finalizer
  3.3 Namespace is not deleted
4. We recover `cluster2`
5. Once `cluster2` is up and running, the namespace is deleted

For the 2nd scenario, the followed steps were:

1. `test-namespace` distributed across `cluster1` and `cluster2`
2. `cluster2` goes offline
3. We delete `cluster2` from the control plane and the cluster registry
  3.1 `oc delete federatedcluster cluster2 -n federation-system`
  3.2 `oc delete cluster cluster2 -n kube-multicluster-public`
4. We run `oc delete namespace test-namespace`
5. Namespace is deleted

Let's wait for the next release which will include `--force` option for kubefed2 unjoin. 

The issue can be closed.

Thanks!

**Comment by marun** [comment]
Thank you for the detailed report!  I'm going to hold the issue open for now to ensure the docs are updated to cover deletion.

**Comment by marun** [comment]
The docs have been updated: https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#deletion-policy
