### ISSUE TITLE
kubefed2 disable should support the use of kind and short name

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#608]
**What would you like to be added**:

`kubefed2 disable` only supports identifying the type config to enable by name (group-qualified plural name e.g. deployment.apps).  It should be possible to specify kind (Deployment) or short name (deploy) as well, as is already possible with `kubefed2 enable`.  Only if an api resource is not available (e.g. mycrd.mygroup was deleted before the associated federated type config) should the name of the type config be mandatory.  

**Why is this needed**:

enable/disable should be consistent in the type of identifiers they support.

**Note**: 

The search for an api resource in `enable` currently stops at the first match it finds.  It should be checking that the provided identity is not ambiguous and matches only one api resource.  In the case of deployments, both `deployment.apps` (desired) and `deployments.extensions`(legacy) will be matched by the kind `Deployment` and the short name `deploy`.   If the search finds more than one api resource, it should report an error indicating that a group-qualified plural name must be provided.

/kind feature

**Comment by marun** [comment]
It will also be useful for #607 to support providing kind or short name to identify the type of the resource targeted for federation.

cc: @irfanurrehman

**Comment by irfanurrehman** [comment]
> It will also be useful for #607 to support providing kind or short name to identify the type of the resource targeted for federation.

@marun Acknowledge, and it makes more sense, and while implementing 607, did think about it too. I can take this up for both disable and federate, however would prefer to do it post #607.

**Comment by marun** [comment]
@irfanurrehman I've spoken with @xunpan and he's agreed to take responsibility for resolving this issue.  He wanted to help with the beta and I identified this issue as something that could proceed in parallel to your efforts.

**Comment by irfanurrehman** [comment]
> @irfanurrehman I've spoken with @xunpan and he's agreed to take responsibility for resolving this issue. He wanted to help with the beta and I identified this issue as something that could proceed in parallel to your efforts.

@maru Ack, @xunpan thanks!
