### ISSUE TITLE
Federated namespace placement doesn't recreate namespace after adding cluster back in

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/federation-v2#64]
Going through instructions at https://github.com/font/k8s-example-apps/tree/master/sample-fed-v2-demo, particularly step https://github.com/font/k8s-example-apps/tree/master/sample-fed-v2-demo#update-federatednamespaceplacement, the `test-namespace` is successfully removed from `us-east` after updating the namespace placement to remove `us-east` from the list of clusters.

But when the cluster `us-east` is added back in, the `test-namespace` does not get recreated in the `us-east` cluster causing all the other resources to no get added back due to for example:

```
E0426 19:44:46.756125       1 controller.go:617] Failed to execute updates for FederatedReplicaSet "test-namespace/test-replicaset": [Failed to create FederatedReplicaSet "test-namespace/test-replicaset" in cluster us-east: namespaces "test-namespace" not found]
```
Waiting long enough will eventually see the `test-namespace` created, possibly because the watch operation expires and the controller retries a list operation.

If you restart the federation pod, the `test-namespace` will quickly reappear in the `us-east` cluster after the controller receives the list of namespaces and namespace placements. The rest of the resources (configmap, secret, replicaset) then reappear as well once the `test-namespace` exists.

**Comment by marun** [comment]
Fixed by #65.
