### ISSUE TITLE
CI failed in Leader Elector

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/federation-v2#642]
**Which test(s) are failing**:
`Leader Elector`

**Since when has it been failing**:
Since today

**Reason for failure**:
```
Mar 12 02:28:53.629: INFO: Timed out waiting to become leader, err: timed out waiting for the condition
panic: 
Your test failed.
```
**Anything else we need to know**:
The case is not synchronized, so it is not to be executed independently.

/kind failing-test

**Comment by shashidharatd** [comment]
@xunpan, Can you give more context.
Which type of test are you executing. unit/e2e test? managed/unmanaged?
what is the command you used to execute test?

Note: It has been passing in CI.

**Comment by shashidharatd** [comment]
@xunpan, never mind. here is one more instance of failed CI log https://travis-ci.org/kubernetes-sigs/federation-v2/builds/505079399?utm_source=github_status&utm_medium=notification
