### ISSUE TITLE
kubefed2 installtion guide missing in userguide

### ISSUE THREAD

**Issue by poothia** [kubernetes-sigs/federation-v2#654]
**What would you like to be added**:
Going throught the userguide prerequisites, there should be a (optional) guide on how to install "kubefed2".

**Why is this needed**:
"kubefed2" tool is used in many commands mentioned in userguide document.

/kind docs

**Comment by marun** [comment]
The binary is provided as part of a release, and the user can invoke it directly or put it in their path.    This seems pretty basic to me, and not necessarily worth documenting.  Are there additional material you think would be helpful?

**Comment by digivava** [comment]
As someone new to working with open-source software in an alpha state, I was lost for awhile trying to find it as well. I had assumed that the Prerequisites section contained all the info on binaries needed to run the deployment scripts.

It might be helpful just to add the first sentence of your comment above into the prerequisite section of the docs.

**Comment by poothia** [comment]
> The binary is provided as part of a release, and the user can invoke it directly or put it in their path. This seems pretty basic to me, and not necessarily worth documenting. Is there additional material you think would be helpful?

@marun Ya I do agree, but for a new person it is quite confusing. Because there is mention of where to find the "kubefed2" file. So maybe a note in pre-requisites section might be helpful.



> As someone new to working with open-source software in an alpha state, I was lost for awhile trying to find it as well. I had assumed that the Prerequisites section contained all the info on binaries needed to run the deployment scripts.
> 
> In the scripts it seems to be invoked from ./bin. Where did bin come from? Should I be generating it somehow? It might be helpful just to add a little more detail into the prerequisite section of the docs.

@digivava Ya I too got confused. I dont feel it is necessary but a little more clarity would be of no harm.

**Comment by shashidharatd** [comment]
@poothia, are you interested in working on this task?

**Comment by xunpan** [comment]
/assign

Let me handle it for beta
