### ISSUE TITLE
Kubefed2 enable with wrong federation namespace leaves federated type half created

### ISSUE THREAD

**Issue by cwilkers** [kubernetes-sigs/federation-v2#656]
**What happened**:
`kubefed2 enable Namespace` was run on a cluster where the federation-namespace was not `federation-system` as expected by default.

Output was 
```
$ kubefed2 enable -v 2 Namespaces
I0315 09:23:47.528247   17456 enable.go:199] Found resource "namespaces.core/v1"
customresourcedefinition.apiextensions.k8s.io/federatednamespaces.types.federation.k8s.io created
F0315 09:23:48.024766   17456 enable.go:109] error: Error creating FederatedTypeConfig "namespaces": namespaces "federation-system" not found
```
Attempting to then `enable` `Namespace` with the right `federation-namespace` fails:
```
$ kubefed2 enable -v 2 Namespaces --federation-namespace=my-federation
I0315 09:24:18.161717   17508 enable.go:199] Found resource "namespaces.core/v1"
F0315 09:24:18.456461   17508 enable.go:109] error: Error creating CRD "federatednamespaces.types.federation.k8s.io": customresourcedefinitions.apiextensions.k8s.io "federatednamespaces.types.federation.k8s.io" already exists

```
Attempting to then `disable` Namespace fails:
```
$ kubefed2 disable -v 2 Namespaces 
F0315 10:16:25.640939   18831 disable.go:93] error: Error retrieving FederatedTypeConfig "federation-system/Namespaces": federatedtypeconfigs.core.federation.k8s.io "Namespaces" not found
```

**What you expected to happen**:
Sanity checking by `kubefed2 enable` to avoid creating artifacts on a system that it will later refuse to manage.

**How to reproduce it (as minimally and precisely as possible)**:
Install federation in a non-standard NS, e.g. `my-federation`
`kubefed2 enable Namespace`

**Anything else we need to know?**:
Work around:
```
kubectl delete crd federatednamespaces.types.federation.k8s.io
kubefed2 --federation-namespace=my-federation enable Namespace 
```
**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version
- Install method (helm vs script)
- Install configuration (namespaced vs cluster-scoped)
- Others

/kind bug

**Comment by xunpan** [comment]
It makes sense to me.
We need basic sanity check. Though it is not a full transaction, it covers the most case that a user federates a resource carelessly.

**Comment by xunpan** [comment]
After fixed in https://github.com/kubernetes-sigs/federation-v2/pull/628, existing CRD will not break `enable` operation. In such case, even the partial success case left a federated* CRD, it is fine to reuse this in a correct `enable` operation in correct namespace. So, it is functional correct.

However, it is not good experience to have such a partial succeed in basic case. Let me fix it.
