### ISSUE TITLE
Overrides field should not be capitalized in yaml serialization

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#66]
This should be `overrides` when serialized, per: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#naming-conventions

**Comment by shashidharatd** [comment]
@pmorie, does this issue still exist? otherwise can you close this.

**Comment by font** [comment]
This was fixed by https://github.com/kubernetes-sigs/federation-v2/commit/ada272855ee5155491e97a98eeef3baa54c202a3.
