### ISSUE TITLE
Mechanism to identify a resource created by user vs created by federation control plane

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes-sigs/federation-v2#668]
**What would you like to be added**:
Mechanism to differentiate API resources (or just called resource here after) created by federation control plane from user created resources in member clusters.

**Why is this needed**:
It might be required by some controllers, or visualization tools to differentiate the resources based on who owns the resources. It might also aid in debugging some specific issues.

/kind feature

**Comment by marun** [comment]
Note that I'm targeting labeling of federated resources in #612.  An extension to that labeling could be adding a configuration option to determine whether existing resources that lack the label are adopted or left alone (likely resulting in a propagation error being reported in status).

**Comment by shashidharatd** [comment]
Cool, Good to know. Thanks !

**Comment by marun** [comment]
@shashidharatd Will this be addressed to your satisfaction by #715?

**Comment by irfanurrehman** [comment]
I think this should centainly be taken care by #715. 
Also https://github.com/kubernetes-sigs/federation-v2/issues/612 takes care or majority of other scenario.

The only missing piece I think remains as an option for the user (via a configuration) to control the behaviour of adoption. @shashidharatd as per out last talk, are you intending to implement that?

**Comment by shashidharatd** [comment]
Closing this one as per above comment and have opened https://github.com/kubernetes-sigs/federation-v2/issues/805 for the missing part.
