### ISSUE TITLE
Federated Status will not reconcile when federation has no readyCluster 

### ISSUE THREAD

**Issue by braceinhz** [kubernetes-sigs/federation-v2#677]
**What happened**:Federated Status will not reconcile when federation has no readyCluster 

**How to reproduce it (as minimally and precisely as possible)**:when federation has no readycluster, and we have already deploy federatedresource such as nginx federateddeployment, the controller will report err 
```E0321 16:35:40.655125      10 controller.go:313] Failed to update status object for federated type FederatedDeploymentStatus "default/caoyu": FederatedDeploymentStatus.core.federation.k8s.io "caoyu" is invalid: []: Invalid value: map[string]interface {}{"clusterStatus":interface {}(nil), "kind":"FederatedDeploymentStatus", "metadata":map[string]interface {}{"resourceVersion":"191617", "generation":1, "creationTimestamp":"2019-03-20T13:43:23Z", "ownerReferences":[]interface {}{map[string]interface {}{"apiVersion":"types.federation.k8s.io/v1alpha1", "kind":"FederatedDeployment", "name":"caoyu", "uid":"2197d6ba-4b16-11e9-b803-0255c0a80024"}}, "name":"caoyu", "namespace":"default", "selfLink":"/apis/core.federation.k8s.io/v1alpha1/namespaces/default/federateddeploymentstatuses/caoyu", "uid":"219a30dd-4b16-11e9-b803-0255c0a80024"}, "apiVersion":"core.federation.k8s.io/v1alpha1"}: validation failure list:```
```clusterStatus in body must be of type array: "null"```

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.3-r1-CCE2.0.17.B003", GitCommit:"df1a90c11bd86b0bdd0685ed8a973500dd9b37ba", GitTreeState:"clean", BuildDate:"2018-12-05T08:07:00Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.1-r1-CCE2.0.13.B002-28-g4da8bcc4d945df", GitCommit:"4da8bcc4d945df6b45f9da1965bdb06de8ca59dd", GitTreeState:"clean", BuildDate:"2018-11-06T12:05:05Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Federation version v0.0.6
- Install method script

Suggest:
Please check [code here](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/controller/status/controller.go#L303)
`existingStatus.Object["clusterStatus"] = status.Object["clusterStatus"]`
here clusterStatus can be nil after `util.GetUnstructured`, and this couse err occured, this will couse federatedresource status not reconcile,

/kind bug

**Comment by irfanurrehman** [comment]
@braceinhz thanks for reporting this. Seemingly you have done some debugging to pinpoint the cause, do u want to propose a fix.

**Comment by braceinhz** [comment]
@irfanurrehman With pleasure , I propose a PR: https://github.com/kubernetes-sigs/federation-v2/pull/692

**Comment by shashidharatd** [comment]
This has been addressed with https://github.com/kubernetes-sigs/federation-v2/pull/692
