### ISSUE TITLE
Member cluster's nodes may deployed in muti availability zone

### ISSUE THREAD

**Issue by Dingshujie** [kubernetes-sigs/federation-v2#678]
What would you like to be added:
FederatedClusterStatus.Zone use []string instead of string, and generate multiple AZ level dns name.

Why is this needed:
Now, FederatedCluster status Region and Zone use first node Region and Zone.
A lot of Cluster's nodes may deployed in muti availability zones, this field may in influence dns enpoint controller to generate dns record name,  dnsname of az-level dns name may be incorrect.

/kind feature

**Comment by marun** [comment]
@shashidharatd What are your thoughts on this issue?

**Comment by shashidharatd** [comment]
IMHO, the cross-cluster service discovery feature should be able to work with multi-zone clusters. logically, there should be no issues. But we have to try and test it. I would try to put up a PR in coming days.
