### ISSUE TITLE
Ensure that the federated control plane is minimally privileged

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#687]
#670 revealed that the helm chart was not granting sufficient privileges to the control plane.  While it is tempting to just use the cluster-admin role, it should be possible to grant only the privileges required.  For some types, the scope of privilege will depend on how the control plane is deployed (namespaced or cluster-scoped):

 - `get/watch/list/update`
   - `(multiclusterdns|scheduling|types).federation.k8s.io` 
      - namespaced: federation namespace
      - cluster-scoped: *
   - `FederatedTypeConfig` 
       - federation namespace
   - `FederatedCluster` 
       - federation namespace
   - `PropagatedVersion` 
       - namespaced: federation namespace
       - cluster-scoped: *
   - `ClusterPropagatedVersion` 
       - cluster-scoped: *
 - `get/list/watch`
   - `Namespace`
      - cluster-scoped: *
 - `get`
   - `Cluster` 
       - cluster registry namespace
   - `Secret` (for cluster auth)
       - federation namespace

For member clusters, the permissions required by the local service account would depend on the enabled types:

 - `get/watch/list/update`
   - any type intended to be managed by federation
      - namespaced: federation namespace
      - cluster-scoped: *

If the goal was avoiding the use of the cluster-admin role in member clusters, it would be necessary to coordinate the rbac permissions of member cluster service accounts with the types enabled for federation.

cc: @xunpan @pmorie

**Comment by xunpan** [comment]
For leader elector, `configmaps`, `secrets` needs RBAC based on my test, and we also have `events`, so it needs RBAC too.

I will check detailed operation verbs for these resources.

**Comment by xunpan** [comment]
I've already fixed this in https://github.com/kubernetes-sigs/federation-v2/pull/710. But it seems not make it closed automatically. 

@marun please close this ticket if there is no other concern.

**Comment by marun** [comment]
@xunpan I think there is still a bit more work to reduce the control plane permissions for built-in types to a minimum:

- secrets should only have 'get', and only in the federation namespace for the cluster role
- namespaces should not have 'patch', 'create', or 'update'
- configmaps should have not 'patch' (and maybe not list or watch?  it's only used for leader election afaik) and only in the federation namespace for the cluster role
- do events need 'list' or 'watch'?

**Comment by marun** [comment]
@xunpan I would like to see secret and configmap permissions limited to the federation namespace as per [my comment on #796](https://github.com/kubernetes-sigs/federation-v2/pull/796#pullrequestreview-230702861) before this is closed.
