### ISSUE TITLE
federation v2 deployment error

### ISSUE THREAD

**Issue by skochetkov** [kubernetes-sigs/federation-v2#693]
Hi,
I am trying to install latest (master) v2 following the user guide (executed all steps: download binary, go path etc). But getting the error. Please see my output below: 

> ~/space/go/src/github.com/kubernetes-sigs/federation-v2$ ./scripts/deploy-federation-latest.sh k8s-cluster-04
> namespace/federation-system created
> namespace/kube-multicluster-public created
> clusterrolebinding.rbac.authorization.k8s.io/federation-admin created
> clusterrole.rbac.authorization.k8s.io/federation-role created
> clusterrolebinding.rbac.authorization.k8s.io/federation-rolebinding created
> customresourcedefinition.apiextensions.k8s.io/clusterpropagatedversions.core.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/federatedclusters.core.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/federatedservicestatuses.core.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/federatedtypeconfigs.core.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/propagatedversions.core.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/dnsendpoints.multiclusterdns.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/domains.multiclusterdns.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/ingressdnsrecords.multiclusterdns.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/servicednsrecords.multiclusterdns.federation.k8s.io created
> customresourcedefinition.apiextensions.k8s.io/replicaschedulingpreferences.scheduling.federation.k8s.io created
> deployment.apps/federation-controller-manager created
> customresourcedefinition.apiextensions.k8s.io/clusters.clusterregistry.k8s.io created
> error: unable to retrieve the complete list of server APIs: clusterregistry.k8s.io/v1alpha1: the server could not find the requested resource, core.federation.k8s.io/v1alpha1: the server could not find the requested resource, multiclusterdns.federation.k8s.io/v1alpha1: the server could not find the requested resource, scheduling.federation.k8s.io/v1alpha1: the server could not find the requested resource
> Waiting for propagation of the clusterregistry CRD.error: unable to retrieve the complete list of server APIs: clusterregistry.k8s.io/v1alpha1: the server could not find the requested resource, core.federation.k8s.io/v1alpha1: the server could not find the requested resource, multiclusterdns.federation.k8s.io/v1alpha1: the server could not find the requested resource, scheduling.federation.k8s.io/v1alpha1: the server could not find the requested resource
> .error: unable to retrieve the complete list of server APIs: clusterregistry.k8s.io/v1alpha1: the server could not find the requested resource, core.federation.k8s.io/v1alpha1: the server could not find the requested resource, multiclusterdns.federation.k8s.io/v1alpha1: the server could not find the requested resource, scheduling.federation.k8s.io/v1alpha1: the server could not find the requested resource
> .error: unable to retrieve the complete list of server APIs: clusterregistry.k8s.io/v1alpha1: the server could not find the requested resource, core.federation.k8s.io/v1alpha1: the server could not find the requested resource, multiclusterdns.federation.k8s.io/v1alpha1: the server could not find the requested resource, scheduling.federation.k8s.io/v1alpha1: the server could not find the requested resource
> .error: unable to retrieve the complete list of server APIs: clusterregistry.k8s.io/v1alpha1: the server could not find the requested resource, multiclusterdns.federation.k8s.io/v1alpha1: the server could not find the requested resource, scheduling.federation.k8s.io/v1alpha1: the server could not find the requested resource
> . done
> customresourcedefinition.apiextensions.k8s.io/federatedclusterroles.types.federation.k8s.io created
> federatedtypeconfig.core.federation.k8s.io/clusterroles.rbac.authorization.k8s.io created in namespace federation-system
> F0326 17:11:31.231139   13099 enable.go:112] error: Error listing api resources: unable to retrieve the complete list of server APIs: types.federation.k8s.io/v1alpha1: the server could not find the requested resource

Here's what I am currently have:
```
$ kubectl get serviceaccounts default --namespace federation-system -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2019-03-26T21:11:24Z
  name: default
  namespace: federation-system
  resourceVersion: "645428"
  selfLink: /api/v1/namespaces/federation-system/serviceaccounts/default
  uid: b619dd20-500b-11e9-b165-005056b30227
secrets:
- name: default-token-gjcjz

~/space/go/src/github.com/kubernetes-sigs/federation-v2$ kubectl get namespaces
NAME                       STATUS   AGE
default                    Active   4d1h
federation-system          Active   8m31s
kube-multicluster-public   Active   8m31s
kube-public                Active   4d1h
kube-system                Active   4d1h
pks-system                 Active   4d
```

I tried to delete and install again several times but no luck....
Any help will be very welcome!
Thanks

/kind bug

**Comment by marun** [comment]
Please follow the helm instructions.   The script-based deployment is not supportable, and I will be moving references from the userguide to the devguide this afternoon.

**Comment by marun** [comment]
Also, the best place to get support is the #sig-multicluster channel on kubernetes.slack.com.

**Comment by skochetkov** [comment]
Thank you!

**Comment by marun** [comment]
Closing, as this appears to be a support request that has been resolved.
