### ISSUE TITLE
Ensure CI tests against the most recent release version of kube

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#699]
As discovered in #698, CI is currently testing against kube 1.12.  The managed fixture test run sources a `kube-apiserver` binary from the kubebuilder archive, and the version of kubebuilder we're currently stuck on provides a 1.12 `kube-apiserver`.   The unmanaged fixture test run uses a pinned version of kind that uses kube 1.12.  To resolve this issue:

 - [x] Update to latest version of kubebuilder (#208 should resolve this)
 - [x] Update to latest version of kind (fixed by #700)

Going forward it will be important to coordinate the versions of kube provided by by kind and kubebuilder.

**Comment by shashidharatd** [comment]
@marun, can we close this issue?

**Comment by marun** [comment]
@shashidharatd Closing!
