### ISSUE TITLE
kubefed2 disable should delete the FTC rather than set propagationEnabled

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#721]
`kubefed2 enable` adds the crd and ftc necessary for federation of a type.  Currently `kubefed2 disable` sets `propagationEnabled: false` on the target FTC (and deletes the crd and ftc if `--delete-from-api=true` is provided).  Instead, `kubefed2 disable` should be the reverse of `enable` and delete the target FTC and optionally the crd.  A user can edit the FTC if they want to disable propagation.

/kind bug

**Comment by marun** [comment]
As part of this bug, the `disable` command should return without error if the type is already disabled.

**Comment by marun** [comment]
When optionally deleting the crd, `kubefed2` should delete the ftc (which will ensure the sync controller is stopped) and then iterate over all instances of the crd and remove the federation finalizer to ensure that garbage collection is possible.  Only then should deletion of the crd be attempted.

**Comment by font** [comment]
Closing this as fixed by #769. I've created a new issue https://github.com/kubernetes-sigs/federation-v2/issues/829 to track handling the deletion of custom resources.
