### ISSUE TITLE
ExternalDNS deployment failure on AWS (source: CRD and provider:coreDNS)

### ISSUE THREAD

**Issue by cmclopes** [kubernetes-sigs/federation-v2#726]
**What happened**:
I'm following the user guide to enable the federation DNS for Ingress and Service using the coreDNS as the provider (https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/ingress-service-dns-with-coredns.md), and I can't go further the ExternalDNS installation step (https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/ingress-service-dns-with-coredns.md#installing-externaldns) because the pod ends in error:

```
[clopes@localhost federation]$ k --context=aws logs external-dns-586d5555dc-pgfjk
time="2019-04-04T09:56:46Z" level=info msg="config: {Master: KubeConfig: RequestTimeout:30s IstioIngressGatewayServices:[istio-system/istio-ingressgateway] Sources:[crd] Namespace: AnnotationFilter: FQDNTemplate: CombineFQDNAndAnnotation:false IgnoreHostnameAnnotation:false Compatibility: PublishInternal:false PublishHostIP:false ConnectorSourceServer:localhost:8080 Provider:coredns GoogleProject: DomainFilter:[] ZoneIDFilter:[] AlibabaCloudConfigFile:/etc/kubernetes/alibaba-cloud.json AlibabaCloudZoneType: AWSZoneType: AWSZoneTagFilter:[] AWSAssumeRole: AWSBatchChangeSize:1000 AWSBatchChangeInterval:1s AWSEvaluateTargetHealth:true AWSAPIRetries:3 AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup: CloudflareProxied:false CloudflareZonesPerPage:50 RcodezeroTXTEncrypt:false InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true InfobloxView: DynCustomerName: DynUsername: DynPassword: DynMinTTLSeconds:0 OCIConfigFile:/etc/kubernetes/oci.yaml InMemoryZones:[] PDNSServer:http://localhost:8081 PDNSAPIKey: PDNSTLSEnabled:false TLSCA: TLSClientCert: TLSClientCertKey: Policy:sync Registry:txt TXTOwnerID:default TXTPrefix: Interval:1m0s Once:false DryRun:false LogFormat:text MetricsAddress::7979 LogLevel:debug TXTCacheInterval:0s ExoscaleEndpoint:https://api.exoscale.ch/dns ExoscaleAPIKey: ExoscaleAPISecret: CRDSourceAPIVersion:multiclusterdns.federation.k8s.io/v1alpha1 CRDSourceKind:DNSEndpoint ServiceTypeFilter:[] RFC2136Host: RFC2136Port:0 RFC2136Zone: RFC2136Insecure:false RFC2136TSIGKeyName: RFC2136TSIGSecret: RFC2136TSIGSecretAlg: RFC2136TAXFR:false}"
time="2019-04-04T09:56:46Z" level=info msg="Created Kubernetes client https://172.20.0.1:443"
time="2019-04-04T09:56:46Z" level=fatal msg="error listing resources in GroupVersion \"multiclusterdns.federation.k8s.io/v1alpha1\": the server could not find the requested resource"
```
This only happens on my AWS EKS cluster. No problem found on my Azure AKS cluster (where the federation control plan runs).

**What you expected to happen**:

The ExternalDNS being up and running on AWS as well to be able to proceed with the installation of the MetalLB.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the clusters on both cloud providers
2. Deploy the federation control plane as described here (https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#automated-deployment)
3. Setup the Federation DNS for Ingress and Service (https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/ingress-service-dns-with-coredns.md#federation-dns-for-ingress-and-service)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
Azure: 1.11.8
AWS: 1.11.8-eks-7c34c0

- Federation version
Federation v2 controller-manager version: version.Info{Version:"v0.0.7", GitCommit:"3e251608ca5357080b95a0bedc45759652f17d29", GitTreeState:"clean", BuildDate:"2019-03-22T22:30:26Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- Install method (helm vs script)
Mixed. Federation with the script, helm used to install the etcd-operator and coredns.

- Install configuration (namespaced vs cluster-scoped)

- Others

/kind bug

**Comment by marun** [comment]
ExternalDNS needs to run on the host cluster so it has access to the resources that federation creates.  It does not have to run on each member cluster.  It appears that you are trying to run ExternalDNS on a cluster other than the one hosting the federation control plane.  

FYI, please use helm to deploy federation, as script-based deployment is developer-only and not supportable (and has been removed from master to reflect that).  Make sure to specify the image tag as a release version to get the appropriate tag (e.g. `v0.0.7`) instead of the canary image used in CI: 

https://github.com/kubernetes-sigs/federation-v2/blob/master/charts/federation-v2/values.yaml#L13

Please close this issue if your support request has been satisfied, and feel free to reach out on the #sig-multicluster on https://kubernetes.slack.com for further assistance.

**Comment by cmclopes** [comment]
@marun Thanks for your response.  Yes, you are right, I was trying to deploy the external DNS on both clusters (my bad). I also followed your suggestion of using the helm to install the federation control plan and use the release 0.0.7 instead of the canary.

It's fully working now (with the sample project), and the DNS is propagated to the AzureDNS like a charm.

I am closing this ticket.

Thanks for your help.

PS: I don't have access to the slack. Can you send me an invite, please?

**Comment by marun** [comment]
@cmclopes I'm glad our issue has been resolved.  It should be possible to get an invite via https://slack.k8s.io/
