### ISSUE TITLE
FederationConfig enhancement

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/federation-v2#729]
**What would you like to be added**:
following up actions after add FederationConfig resources in #685:
- [ ] change helm chart to use FederationConfig for controller options for both namespaced and cluster scoped clusters.
- [ ] remove command line options
- [ ] make kubectl disable reject in namespaced federation.
- [ ] update document to reflect the changes
- [ ] --federation-config=myfile.yaml

**Why is this needed**:

/kind feature

**Comment by marun** [comment]
@xunpan I've added a separate issue to track configuring kubefed2 with FederationConfig: #748

**Comment by xunpan** [comment]
@marun I will handle it
