### ISSUE TITLE
Use the dynamic client for interacting with the cluster-registry

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#73]
So that we don't need to vendor the client. This will ease the transition to the CRD-based cluster registry when the time comes.

See also: https://github.com/kubernetes/cluster-registry/pull/225

**Comment by font** [comment]
CRD-based cluster registry is now available. Not sure if we need to move to a dynamic client for interacting with it unless vendoring in the client continues to be problematic.

**Comment by marun** [comment]
I believe the agreed strategy is to continue vendoring the generated cluster registry client to ensure the robustness of interaction with the cluster CRD (retrieval of api endpoints as part of push reconciliation and addition of cluster as part of cluster join).  Feel to reopen if that's not the case.
