### ISSUE TITLE
Transition to kubebuilder

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#74]
Federation v2 is currently based on [apiserver-builder](https://github.com/kubernetes-incubator/apiserver-builder), which automates the creation of API types and deployment of an aggregated API server to expose created types.  An aggregated API server imposes considerable operational cost and complexity, and it is desirable to remove this requirement in preparation for an alpha release.   [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) provides a CRD-based alternative to apiserver-builder to transition to.  The following strategy is suggested:

- [ ] Transition the primitives of one or more federated types (e.g. Secrets) to CRDs
- [ ] Create a generic webhook that can validate the type resource embedded in a template resource
- [ ] Transition the primitives for all supported types to CRD
- [ ] Reboot the repo with kubebuilder
- [ ] Transition system types (`FederatedCluster`, `PropagatedVersion`, `FederatedTypeConfig`) to CRD 

A goal in transitioning to CRDs is to maintain the same quality of validation for the resources embedded in templates as is currently provided by first-class API types.  The following strategy is suggested:

 - For a given template resource (e.g. `FederatedSecret`), find the `FederatedTypeConfig` that specifies the template type
 - For the target type of the `FederatedTypeConfig`, retrieve the OpenAPI spec
 - Validate the target resource embedded in the template with the OpenAPI spec

**Comment by font** [comment]
The validation work is now tracked by #116.

**Comment by marun** [comment]
This is implemented by #120.
