### ISSUE TITLE
Propagation status should be recorded on federated resources

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#740]
There have been a number of issues filed that suggest the value of the sync controller writing per-resource status and per-cluster status to aid in troubleshooting, including but not limited to:

 - Federation of placement stops when clusterName duplicated in override (#588)
 - Jobs are not updated when federated jobs are changed (and status does not show this) (#574)

The consensus seems to be that propagation status be recorded on each reconciliation loop, as per the following design doc:

https://docs.google.com/document/d/15SQ3y4Mx4nV1kWB-7i-bzRzmN8TVmNoJ6_mMSVDSZfk/edit

**Comment by Joseph-Irving** [comment]
Has there been any discussion around including more detailed statuses that have some basic info about the state of the resource in each cluster? e.g for a deployment:
```
status:
- name: clusterA
  propagation: ok
  availableReplicas: 5
- name: clusterB
  propagation: ok
  availableReplicas: 3
```
This would make our lives a lot easier, as iterating over all our kube contexts to check if the deployment succeeded can be a bit awkward. There would still be scenarios where you would need to go into an individual cluster to work out what went wrong, but if we could get some high level info just from the federated resource it would simplify things.

**Comment by marun** [comment]
> Has there been any discussion around including more detailed statuses that have some basic info about the state of the resource in each cluster? e.g for a deployment:

Yes. Federation is intended to be general-purpose, so including custom behavior to collect arbitrary status for any type is unlikely.  Scalable resources (deployments, replicasets) are likely to be an exception, though, since aggregating those details locally would simplify scheduling mechanisms.
