### ISSUE TITLE
support optional values in FederationConfig 

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/federation-v2#770]
**What would you like to be added**:
support optional filed in `FederationConfig` yaml.

Currently, default values of `FederationConfig` is not supported in yaml file. 
If a field in yaml file is not specified, the default value in yaml but not in controller manager is used. E.g. `cluster-monitor-period` is not specified, it is not `40s` as default but `0s` as default value.

**Why is this needed**:
better usability

/kind feature

**Comment by marun** [comment]
Doing this properly will require a validating webhook, since openapi schema validation does not support defaults.  A good stopgap could be the controller manager observing invalid values (like `0s` for a monitor period) and writing its defaults back to the API.
