### ISSUE TITLE
Rename `limitedScope` option to `scope` or `deploymentScope` for clarity

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#773]
When talking about federation deployment, we talk about 'cluster-scoped' or 'namespace-scoped'.   The option to configure the scope , though, is `limitedScope` in `FederationConfig`, with a value of `true` indicating namespace-scoped and `false` indicating cluster-scoped.  It would be easier to understand if the argument was `scope` or `deploymentScope` and the values were `cluster` and `namespaced` (as per crd scope).

**Comment by xunpan** [comment]
/assign
I will handle this.
