### ISSUE TITLE
Rename `kubefed2` binary

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#799]

**Comment by shashidharatd** [comment]
I can pick this up, if no one else is already working on it. provided we have consensus on the name

**Comment by marun** [comment]
Consensus: `kfctl`

**Comment by gyliu513** [comment]
@marun I think it may not good to use `kfctl` as kubeflow is already using it, please refer to follows:

- https://medium.com/kubeflow/kubeflow-v0-5-simplifies-model-development-with-enhanced-ui-and-fairing-library-78e19cdc9f50
- https://github.com/kubeflow/kubeflow/blob/master/kfctl/README.md

**Comment by marun** [comment]
Thanks @gyliu513.  Revised consensus: `kubefedctl`

cc: @shashidharatd

**Comment by shashidharatd** [comment]
@gyliu513, Thanks for the reference. Agree, that we should not rename to kfctl as there is already such tool in the k8s ecosystem.
How about `kcfctl` --> Kubernetes Cluster federation Ctl?

**Comment by shashidharatd** [comment]
kubefedctl SGTM
