### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by wpieterse** [kubernetes-sigs/federation-v2#81]
Hi there, not much an issue but I dont know where else to post it. Where can I find a timeline for when v2 will reach beta stage, if there is one? Also, is there a setup guide for how to create a test cluster with v2?

**Comment by font** [comment]
@wpieterse If you're looking for a user's guide, we still need to create one, but the best way to set it up right now is to create your kubernetes clusters with minikube or using your preferred cloud provider, then using the [deploy federation script](https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/deploy-federation.sh) to automate the deployment. Make sure to [follow the instructions in the comments of the script](https://github.com/kubernetes-sigs/federation-v2/blob/6ae6ce619ca9fb9090319b20c331ad71abc806e3/scripts/deploy-federation.sh#L26-L41). The script basically runs through the [unmanaged E2E testing instructions in the README](https://github.com/kubernetes-sigs/federation-v2#unmanaged-and-hybrid-cluster-setup) up until you're ready to run `go test`.

If you're looking for an example tutorial to use with v2 you can try out the [sample-fed-v2-demo](https://github.com/font/k8s-example-apps/tree/master/sample-fed-v2-demo) or for more advanced tutorials you can refer to the link provided by @onyiny-ang. These tutorials need to be slightly updated to reflect the latest changes that have been recently merged into v2.

**Comment by wpieterse** [comment]
Yes this is perfect! Im still a while away from starting to run anything in production, I just want to take it for a test drive and see what it does. My plan is to eventually run my mobile game backend with this. Thanks for the comments!
