### ISSUE TITLE
failed to install via helm

### ISSUE THREAD

**Issue by freegroup** [kubernetes-sigs/federation-v2#810]
**What happened**:
Installing kube.fed-v2 vi helm reports an error
```
helm install fedv2-charts/federation-v2 --version=0.0.9 --namespace federation-system
Error: apiVersion "core.federation.k8s.io/v1alpha1" in federation-v2/templates/federatedtypeconfig.yaml is not available
```

I add the helm repo for the fed-v2 before
``` 
 helm repo add fedv2-charts https://raw.githubusercontent.com/kubernetes-sigs/federation-v2/master/charts

helm repo list
NAME            URL                                                                          
stable          https://kubernetes-charts.storage.googleapis.com                             
local           http://127.0.0.1:8879/charts                                                 
svc-cat         https://svc-catalog-charts.storage.googleapis.com                            
fedv2-charts    https://raw.githubusercontent.com/kubernetes-sigs/federation-v2/master/charts


helm search federation-v2
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                        
fedv2-charts/federation-v2      0.0.9                           Kubernetes Federation V2 helm chart

``` 
**What you expected to happen**:
the fed-v2 control plane is installed without any errors

**Environment**:
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"} 
```
- Federation version: 0.0.9
- Install method (helm vs script): helm
- Install configuration (namespaced vs cluster-scoped): cluster-scoped
- Others

/kind bug

**Comment by HaraldGustafsson** [comment]
I had the same issue but after removing the CRDs and other things (as explained in deleting federation) and run it a second time it worked.

**Comment by marun** [comment]
@freegroup As per @HaraldGustafsson's comment, are you deploying to a clean cluster (where fedv2 has not been deployed previously or fedv2 has been removed as per the instructions)?

**Comment by freegroup** [comment]
IT Is a fresh and Clean kubernetes Cluster.

**Comment by marun** [comment]
@freegroup What version of helm are you using?  And have you granted the necessary permissions to the tiller (if rbac is enabled in the host cluster)?  I was not able to reproduce the issue you report (using kube 1.14 helm 2.13) so long as I granted the tiller the necessary permissions (see #817).

**Comment by HaraldGustafsson** [comment]
Clarify that I also installed to a cluster that not previously had fed V2 installed, the deletion was between the attempts. I did not delete the federation system namespace in between. But it worked the second time. The cluster is on VMs on openstack. Maybe a race condition?

**Comment by freegroup** [comment]
I'm using helm in the version below:
```bash
helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

we have RBAC enabled in our cluster. Installation of helm is shown below
```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: ServiceAccount
metadata:
 name: helm
 namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: helm
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: cluster-admin
subjects:
 - kind: ServiceAccount
   name: helm
   namespace: kube-system
EOF

helm init --service-account helm

```

The Kubernetes version is 1.14.0 and it is created via https://gardener.cloud/ . Gardener seems to pass the kubernetes conformance test with 100% (https://k8s-testgrid.appspot.com/conformance-gardener#Gardener,%20v1.14%20AWS). I think nothing special or broken setup should be in the gardener cluster.

I created a new fresh cluster and I have the very same problem.

**Comment by freegroup** [comment]
`brew upgrade kubernetes-helm` is the solution. Sorry for the noise.

```
 helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

maybe it is a good idea to mention which are the required HELM version for the installation 

Thanks for the support!

**Comment by marun** [comment]
@freegroup The helm install instructions already mentions the dependency on helm > 2.10: 

https://github.com/kubernetes-sigs/federation-v2/blob/master/charts/federation-v2/README.md#prerequisites

**Comment by freegroup** [comment]
Thank you again for your patience. Sometimes I accidentally overlook the important things. :-/
