### ISSUE TITLE
kubefed2 release v0.0.9 only contains symlink

### ISSUE THREAD

**Issue by HaraldGustafsson** [kubernetes-sigs/federation-v2#811]
**What happened**:
Downloaded kubefed2 binary release 0.0.9, verified checksum, untared it to find it only contained a sym link to kubefed2-linux and not the actual binary.
 
**What you expected to happen**:
That the actual binary should be included.

**How to reproduce it (as minimally and precisely as possible)**:
as above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version v0.0.9
- Install method (helm vs script)
- Install configuration (namespaced vs cluster-scoped)
- Others

/kind bug

**Comment by marun** [comment]
Thanks for reporting this, fixed!
