### ISSUE TITLE
Add federated StatefulSet and DaemonSet.

### ISSUE THREAD

**Issue by blucruz** [kubernetes-sigs/federation-v2#858]
**What would you like to be added**:I noticed there is federated Deployment in federation. Yet StatefulSet and DaemonSet is not supported. Could we add this two resource to federation?

**Why is this needed**:There is a demand for federated StatefulSet and DaemonSet in federation. 

/kind feature

**Comment by marun** [comment]
@blucruz fedv2 enables a subset of available types by default, and also supports enabling any kube type (including any CRD) as per the documentation:

https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#enabling-federation-of-an-api-type

Please close this issue if the above link satisfies your requirements.
