### ISSUE TITLE
The default system namespace should be prefixed with `kube-`

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#868]
As per the kube api convention [on system namespaces](https://github.com/kubernetes/community/blob/20c1e33a741f238ec0428f7fdc096ca1ff0d862d/contributors/devel/sig-architecture/api-conventions.md#namespace-names), the default federation system namespace should have the `kube-` prefix reserved for system namespaces to avoid collision with user namespaces.  Suggested options:

 - `kube-fed`
 - `kube-fed-system`
 - `kube-federation`
 - `kube-federation-system`

**Comment by sohankunkerkar** [comment]
+1 for `kube-federation-system`
