### ISSUE TITLE
Storing `Cluster` resources outside of the kubefed namespace is a potential security risk

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#869]
As per an observation by @deads2k, storing a `Cluster` resource outside of the kubefed namespace (e.g. in the `kube-multicluster-public` namespace) represents a potential security risk. A user with the appropriate permissions for `Cluster` resources in the cluster registry namespace could change the api endpoint of a `Cluster` to a malicious endpoint that could collect the kubefed credentials for that cluster. His suggestion was that the risk could be avoided if `Cluster` resources were always located in the kubefed system namespace, since access would be localized to the kubefed control plane.

If this security risk outweighs the benefits of sharing a cluster registry, though, it's not clear why kubefed needs to rely on the `Cluster` resource at all.  The fields kubefed cares about (i.e. api endpoints and certs) could be added back to the `FederatedCluster` resource, and use of the registry namespace and cluster registry `Cluster` resources discontinued.

/kind bug

**Comment by pmorie** [comment]
> If this security risk outweighs the benefits of sharing a cluster registry, though, it's not clear why kubefed needs to rely on the Cluster resource at all. The fields kubefed cares about (i.e. api endpoints and certs) could be added back to the FederatedCluster resource, and use of the registry namespace and cluster registry Cluster resources discontinued.

I'm +1 on inlining the fields in the Cluster resource's spec into FederatedCluster's spec because the API mechanics, security implications, and user experience become much easier to reason about. We can still integrate with the cluster-registry if we do that, for example, by having a way to let a user publish a FederatedCluster into the cluster-registry.
