### ISSUE TITLE
Extend ReplicaSchedulingPreferences to support replicasets

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/federation-v2#92]
`ReplicaSchedulingPreferences` is implemented (as in #46) to support deployments using the same name `<ns/name>` as the key to target the low level `FederatedDeployment` resources (template, override and placement). This needs to be extended and implementation made generic, such that the same API schema can be used to target `FederatedReplicaset` also using a targetRef. The following 2 items will need to be implemented for the same.

- [ ] Make the overall code generic (akin to adapter interface) to be able to take different scheduling types.
- [ ] Implement usage of targetRef (kind+name) to specify the target resource of the given preferences used.

**Comment by marun** [comment]
Consider avoiding usage of interfaces for providing generic behavior, and instead rely on the dynamic client as per the example of the CRD-supporting push reconciler.

**Comment by irfanurrehman** [comment]
> Consider avoiding usage of interfaces for providing generic behavior, and instead rely on the dynamic client as per the example of the CRD-supporting push reconciler.

Acknowledge! Meanwhile it seems at many places its encouraged to use typed client rather then dynamic client (I imagine to guarantee type safety). I guess I need some enlightening insights, please ? :)

**Comment by marun** [comment]
My statement was to prod you to investigate the potential benefits of using the dynamic client, not proscribe its use.  The costs of static typing can be excessive verbosity, and the benefits of avoiding it (where appropriate) can be code that is more concise and easier to maintain.

**Comment by marun** [comment]
@irfanurrehman Is this done?

**Comment by irfanurrehman** [comment]
Yes.
/close
